import type { CompositeStrategyDefinition, StrategyDefinition } from "modules/strategy/api";
import type { Candle, DatasetSnapshotRef, Pair, Timeframe } from "modules/market-data/api";
import type { SentimentDatasetSnapshotRef } from "modules/sentiment/api";
export type CandidateStatus = "CREATED" | "QUEUED" | "BACKTESTING" | "RETRY_WAIT" | "PROCESSING_RESULT" | "TERMINAL_FAILURE_PENDING" | "COMPLETED" | "FAILED" | "CANCELLED";
export interface BacktestSubmissionAccepted { candidateId: string; jobId: string; status: CandidateStatus; }
export interface CancellationUnitOfWork {
  kind: "CANCELLATION";
  id: string;
  query?<Row>(text: string, values: unknown[]): Promise<{ rows: Row[] }>;
  run<T>(operation: () => Promise<T>): Promise<T>;
  onRollback(operation: () => Promise<void>): void;
  commit(): Promise<void>;
  rollback(): Promise<void>;
}
export interface CompletionUnitOfWork { kind: "COMPLETION"; id: string; candidateId: string; completionAttemptCount: number; completionClaimToken: string; query?<Row>(text: string, values: unknown[]): Promise<{ rows: Row[] }>; enlist(moduleName: "EVALUATION" | "LEADERBOARD" | "SEARCH"): void; commit?: () => Promise<void>; rollback?: () => Promise<void>; }
export interface ExecutionPolicyInput { policyId?: "TWO_SIDED_ONE_X_V1"; stopLossPercent?: number; takeProfitPercent?: number; }
export interface ExecutionPolicySnapshot { policyId: "TWO_SIDED_ONE_X_V1"; positionPolicyId: "TWO_SIDED_ONE_X_V1"; sizingPolicyId: "FULL_CURRENT_EQUITY_FEE_AWARE_V1"; fillPolicyId: "NEXT_OPEN_OHLC_STOP_FIRST_V2"; oppositeSignalPolicyId: "CLOSE_AND_REVERSE_NEXT_OPEN_V1"; stopLossPercent?: number; takeProfitPercent?: number; warmupCandles: number; sha256: string; }
export interface Trade { id: string; sequence: number; pair: Pair; settlementAsset: string; backtestAttemptId: string; signal: "LONG" | "SHORT"; entryTime: string; marketEntryPrice: number; entryPrice: number; stopLoss: number | null; takeProfit: number | null; exitTime: string; marketExitPrice: number; exitPrice: number; exitReason: "STOP_LOSS" | "TAKE_PROFIT" | "STRATEGY_CLOSE" | "RANGE_END"; quantity: number; notionalEntryValue: number; equityBeforeTrade: number; equityAfterTrade: number; grossProfit: number; feeAmount: number; slippageBps: number; slippageAmount: number; profit: number; resultPercent: number; result: "WIN" | "LOSS" | "BREAKEVEN"; }
export interface CompletedBacktestResult { status: "COMPLETED"; candidateId: string; attemptId: string; workerRuntimeVersion: string; workerRuntimeSha256: string; startedAt: string; completedAt: string; initialCapital?: number; trades: Trade[]; }
export type GeneratorType = "RANDOM" | "DOMAIN_GUIDED" | "GENETIC";
export interface CreateLeaderboardScopeCommand { name: string; datasetSnapshot: DatasetSnapshotRef; sentimentDatasetSnapshot?: SentimentDatasetSnapshotRef; initialCapital: number; feeRatePercent: number; slippageBps: number; warmupCapacityCandles?: number; scoreFormulaId: string; riskPolicy?: { stopLossPercent?: number; takeProfitPercent?: number }; workerRuntimeVersion: string; workerRuntimeSha256: string; evaluationRuntimeVersion: string; evaluationRuntimeSha256: string; }
export interface StartManualBacktestCommand { leaderboardScopeId: string; strategyDefinitions?: StrategyDefinition[]; compositeDefinition?: CompositeStrategyDefinition; strategyDefinitionIds?: string[]; compositeDefinitionId?: string; executionPolicy?: ExecutionPolicyInput; maxAttempts: number; }
export interface SubmitSearchCandidateCommand extends StartManualBacktestCommand { searchRunId: string; iterationNumber: number; generatedBy: GeneratorType; executionPolicy?: ExecutionPolicyInput | ExecutionPolicySnapshot; }
export interface BenchmarkScopeSummary { id: string; name: string; version: number; datasetSnapshot: DatasetSnapshotRef; sentimentDatasetSnapshot?: SentimentDatasetSnapshotRef; workerRuntimeVersion: string; workerRuntimeSha256: string; evaluationRuntimeVersion: string; evaluationRuntimeSha256: string; simulatorVersion?: string; simulatorSha256?: string; benchmarkTimezone?: string; fillPolicyId?: string; oppositeSignalPolicyId?: string; sameCandleOrderingPolicyId?: string; deterministicGuarantee?: string; pair: Pair; timeframe: Timeframe; datasetRange: { from: string; to: string }; datasetSnapshotId: string; datasetSnapshotSha256: string; warmupCapacityCandles: number; initialCapital: number; feeRatePercent: number; slippageBps: number; riskPolicy?: { stopLossPercent?: number; takeProfitPercent?: number }; decimalPolicyId: "MVP_DECIMAL_HALF_UP_V1"; evaluationPolicyId: "MVP_EVALUATION_V1"; scoreFormulaId: string; createdAt: string; }
export interface ReplayVerificationAccepted { replayJobId: string; experimentId: string; status: "QUEUED"; }
export interface ReplayVerificationJob { schemaVersion: 1; replayJobId: string; experimentId: string; mismatchSampleLimit: number; requestedAt: string; }
export type ReplayVerificationResult = { replayJobId: string; experimentId: string; sourceAttemptId: string } & (
  | { status: "QUEUED" | "RUNNING" }
  | { status: "MATCH"; comparedTradeCount: number; mismatches: []; totalMismatchCount: 0; truncated: false }
  | { status: "MISMATCH"; comparedTradeCount: number; mismatches: Array<{ fieldPath: string; expected: string; actual: string }>; totalMismatchCount: number; truncated: boolean }
  | { status: "NON_REPLAYABLE"; failureCode: "MISSING_SNAPSHOT" | "IMPLEMENTATION_ARTIFACT_UNAVAILABLE" | "REPLAY_ARTIFACT_EXPIRED" }
);
export interface CandidateProgress { candidateId: string; origin: "MANUAL" | "SEARCH"; selectionMode: "SINGLE" | "COMPOSITE"; searchRunId?: string; iterationNumber?: number; leaderboardScopeId: string; status: CandidateStatus; attempts: BacktestAttemptProgress[]; maxAttempts: number; activeAttemptNumber?: number; completionAttemptCount: number; completionMaxAttempts: number; completionNextRetryAt?: string; experimentResultId?: string; failureKind?: "RETRY_EXHAUSTED" | "INFRASTRUCTURE" | "COMPLETION_PROCESSING"; failureCode?: string; lastError?: string; warmupCandles?: number; createdAt: string; updatedAt: string; }
export interface BacktestAttemptProgress { attemptId: string; attemptNumber: number; status: "QUEUED" | "RUNNING" | "RETRY_WAIT" | "COMPLETED" | "FAILED" | "CANCELLED"; startedAt: string; completedAt?: string; deliveryAttemptCount?: number; failureCategory?: "RETRYABLE" | "INFRASTRUCTURE" | "CANCELLED_AUDIT"; failureCode?: string; errorMessage?: string; }
export interface BacktestAttemptAudit extends BacktestAttemptProgress { candidateId: string; queueJobId: string; workerRuntimeVersion: string; workerRuntimeSha256: string; tradeCount: number; auditOnly: boolean; fenceToken?: string; leaseExpiresAt?: string; }
export interface ExperimentResult { id: string; ownerUserId?: string; candidateId: string; searchRunId?: string; leaderboardScopeId: string; scoreFormulaId: string; overallScore: number; rankEligible: boolean; }
export interface ExperimentResultSummary extends ExperimentResult { backtestAttemptId: string; compositeDefinitionId: string; compositeDefinition: CompositeStrategyDefinition; datasetSnapshot: DatasetSnapshotRef; sentimentDatasetSnapshot?: SentimentDatasetSnapshotRef; strategyDefinitions: StrategyDefinition[]; executionPolicy?: ExecutionPolicySnapshot; simulatorVersion?: string; simulatorSha256?: string; benchmarkTimezone?: string; fillPolicyId?: string; oppositeSignalPolicyId?: string; sameCandleOrderingPolicyId?: string; deterministicGuarantee?: string; workerRuntimeVersion?: string; workerRuntimeSha256?: string; evaluationRuntimeVersion?: string; evaluationRuntimeSha256?: string; decimalPolicyId?: "MVP_DECIMAL_HALF_UP_V1"; evaluationPolicyId?: "MVP_EVALUATION_V1"; initialCapital?: number; feeRatePercent?: number; slippageBps?: number; totalProfitAmount?: number; endingEquity?: number; wins?: number; losses?: number; breakevens?: number; maxDrawdownAmount?: number; metrics: import("modules/evaluation/api").EvaluationMetrics; trades: Trade[]; createdAt: string; }
export type StrategyVisualizationOverlay =
  | { id: string; strategyDefinitionId: string; kind: "LINE"; label: string; points: Array<{ time: string; value: number }> }
  | { id: string; strategyDefinitionId: string; kind: "ZONE"; label: string; points: Array<{ time: string; low: number; high: number }> }
  | { id: string; strategyDefinitionId: string; kind: "SIGNAL"; label: string; points: Array<{ time: string; value: number; signal: "BUY" | "SELL" | "HOLD" }> };
export interface ExperimentVisualizationMarker { id: string; tradeId: string; sequence: number; kind: "ENTRY" | "STOP_LOSS" | "TAKE_PROFIT" | "EXIT"; side: "LONG" | "SHORT"; time: string; price: number; exitReason?: Trade["exitReason"]; highlighted: boolean; }
export interface ExperimentVisualization { experimentId: string; datasetSnapshot: DatasetSnapshotRef; candles: Candle[]; overlays: StrategyVisualizationOverlay[]; markers: ExperimentVisualizationMarker[]; nextCursor?: string; }
