export type { NewsModuleDependencies } from "../application/ports";
export type { HtmlNewsInterpreter, InterpretedNewsCandidate, NewsObservability, NewsProvider, NewsProviderFailureReason, NewsProviderFailureStage, NewsRepository } from "../application/ports";
import type { NewsModuleDependencies } from "../application/ports";
import type { NewsModulePublicApi } from "./index";
export declare function createNewsModule(deps?: Partial<NewsModuleDependencies>): NewsModulePublicApi;
export { PostgresNewsRepository } from "../infrastructure/postgres-repository";
export type { NewsSqlClient } from "../infrastructure/postgres-repository";
export { COINDESK_RSS_FEED_URL, createCoinDeskRssProvider, createConfiguredNewsProviders } from "../infrastructure/coindesk-rss-provider";
export type { CoinDeskRssProviderOptions } from "../infrastructure/coindesk-rss-provider";
export { createCrawlerNewsProvider } from "../infrastructure/crawler-provider";
export type { CrawlerNewsProviderOptions, CrawlerLimits, FetchedNewsPage } from "../infrastructure/crawler-provider";
