"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createNewsModule = exports.createInMemoryNewsDependencies = exports.readNews = exports.collect = void 0;
const service_1 = require("../application/service");
const defaultService = (0, service_1.createNewsModule)((0, service_1.createInMemoryNewsDependencies)());
const collect = () => defaultService.collect();
exports.collect = collect;
const readNews = () => defaultService.readNews();
exports.readNews = readNews;
var service_2 = require("../application/service");
Object.defineProperty(exports, "createInMemoryNewsDependencies", { enumerable: true, get: function () { return service_2.createInMemoryNewsDependencies; } });
Object.defineProperty(exports, "createNewsModule", { enumerable: true, get: function () { return service_2.createNewsModule; } });
