import type { StrategyArtifactResolver, StrategyCategory, StrategyDefinition, CompositeStrategyDefinition, Strategy, Signal, StrategyPluginDescriptor, CombinationMethod } from "../domain/contracts";
import { createStrategyModule } from "../application/service";
import type { StrategyGenerationSource, StrategyGenerationResult } from "../application/service";
export type { Signal, StrategyCategory, CombinationMethod, Strategy, StrategyDefinition, CompositeStrategyDefinition, StrategyContext, StrategyCandle, StrategyPluginDescriptor, StrategyVisualizationOverlay, StrategyVisualizationOverlayDraft, StrategyFactory, StrategyArtifactResolver, StrategyParameterDescriptor, StrategyRegistry } from "../domain/contracts";
export interface StrategyModulePublicApi { listStrategies(): StrategyPluginDescriptor[]; resolveStrategy(definition: StrategyDefinition): Promise<Strategy>; combineSignals(definition: CompositeStrategyDefinition, signals: Array<{ strategyDefinitionId: string; signal: Signal }>): Signal; buildVisualization(definition: StrategyDefinition, contexts: import("../domain/contracts").StrategyContext[]): import("../domain/contracts").StrategyVisualizationOverlay[]; listDefinitions(userId: string): Promise<StrategyDefinition[]>; readDefinitions(userId: string, ids: string[]): Promise<StrategyDefinition[]>; listComposites(userId: string): Promise<CompositeStrategyDefinition[]>; readComposite(userId: string, id: string): Promise<CompositeStrategyDefinition>; defineStrategy(userId: string, strategyName: string, parameters: Record<string, number | string>): Promise<StrategyDefinition>; defineComposite(userId: string, command: { method: CombinationMethod; components: Array<{ strategyDefinitionId: string; weight: number }>; thresholds?: { buy: number; sell: number } }): Promise<CompositeStrategyDefinition>; generateStrategy(userId: string, source: StrategyGenerationSource): Promise<StrategyGenerationResult>; }
const defaultRuntime = createStrategyModule();
export const listStrategies = (): StrategyPluginDescriptor[] => defaultRuntime.listStrategies();
export const resolveStrategy = (definition: StrategyDefinition): Promise<Strategy> => defaultRuntime.resolveStrategy(definition);
export const combineSignals = (definition: CompositeStrategyDefinition, signals: Array<{ strategyDefinitionId: string; signal: Signal }>): Signal => defaultRuntime.combineSignals(definition, signals);
export const buildVisualization: StrategyModulePublicApi["buildVisualization"] = (definition, contexts) => defaultRuntime.buildVisualization(definition, contexts);
export const listDefinitions: StrategyModulePublicApi["listDefinitions"] = (userId) => defaultRuntime.listDefinitions(userId);
export const readDefinitions: StrategyModulePublicApi["readDefinitions"] = (userId, ids) => defaultRuntime.readDefinitions(userId, ids);
export const listComposites: StrategyModulePublicApi["listComposites"] = (userId) => defaultRuntime.listComposites(userId);
export const readComposite: StrategyModulePublicApi["readComposite"] = (userId, id) => defaultRuntime.readComposite(userId, id);
export const defineStrategy: StrategyModulePublicApi["defineStrategy"] = (userId, strategyName, parameters) => defaultRuntime.defineStrategy(userId, strategyName, parameters);
export const defineComposite: StrategyModulePublicApi["defineComposite"] = (userId, command) => defaultRuntime.defineComposite(userId, command);
export const generateStrategy: StrategyModulePublicApi["generateStrategy"] = (userId, source) => defaultRuntime.generateStrategy(userId, source);
