"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateStrategy = exports.defineComposite = exports.defineStrategy = exports.readComposite = exports.listComposites = exports.readDefinitions = exports.listDefinitions = exports.buildVisualization = exports.combineSignals = exports.resolveStrategy = exports.listStrategies = void 0;
const service_1 = require("../application/service");
const defaultRuntime = (0, service_1.createStrategyModule)();
const listStrategies = () => defaultRuntime.listStrategies();
exports.listStrategies = listStrategies;
const resolveStrategy = (definition) => defaultRuntime.resolveStrategy(definition);
exports.resolveStrategy = resolveStrategy;
const combineSignals = (definition, signals) => defaultRuntime.combineSignals(definition, signals);
exports.combineSignals = combineSignals;
const buildVisualization = (definition, contexts) => defaultRuntime.buildVisualization(definition, contexts);
exports.buildVisualization = buildVisualization;
const listDefinitions = (userId) => defaultRuntime.listDefinitions(userId);
exports.listDefinitions = listDefinitions;
const readDefinitions = (userId, ids) => defaultRuntime.readDefinitions(userId, ids);
exports.readDefinitions = readDefinitions;
const listComposites = (userId) => defaultRuntime.listComposites(userId);
exports.listComposites = listComposites;
const readComposite = (userId, id) => defaultRuntime.readComposite(userId, id);
exports.readComposite = readComposite;
const defineStrategy = (userId, strategyName, parameters) => defaultRuntime.defineStrategy(userId, strategyName, parameters);
exports.defineStrategy = defineStrategy;
const defineComposite = (userId, command) => defaultRuntime.defineComposite(userId, command);
exports.defineComposite = defineComposite;
const generateStrategy = (userId, source) => defaultRuntime.generateStrategy(userId, source);
exports.generateStrategy = generateStrategy;
