FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY tsconfig.base.json ./
COPY modules ./modules
COPY packages ./packages
COPY apps/frontend ./apps/frontend
ARG VITE_MARKET_SOURCE
ARG VITE_MARKET_REST_URL
ARG VITE_MARKET_WS_URL
ARG VITE_AUTH_SOURCE
ARG VITE_AUTH_BASE_URL
ARG VITE_FEATURE_SOURCE
ARG VITE_FEATURE_BASE_URL
ENV VITE_MARKET_SOURCE=$VITE_MARKET_SOURCE \
    VITE_MARKET_REST_URL=$VITE_MARKET_REST_URL \
    VITE_MARKET_WS_URL=$VITE_MARKET_WS_URL \
    VITE_AUTH_SOURCE=$VITE_AUTH_SOURCE \
    VITE_AUTH_BASE_URL=$VITE_AUTH_BASE_URL \
    VITE_FEATURE_SOURCE=$VITE_FEATURE_SOURCE \
    VITE_FEATURE_BASE_URL=$VITE_FEATURE_BASE_URL
RUN npm install && npm run build --workspace @cryptox/frontend
EXPOSE 5173
CMD ["npm", "run", "start", "--workspace", "@cryptox/frontend"]
