import type { MarketDataModuleDependencies } from "../application/ports";
import type { MarketDataModulePublicApi } from "./index";
export declare function createMarketDataModule(deps?: Partial<MarketDataModuleDependencies>): MarketDataModulePublicApi;
export { createMarketDataSnapshotReader } from "./snapshot-reader";
export { createBinanceMarketDataAdapter } from "../infrastructure/binance-adapter";
export type { BinanceAdapterOptions } from "../infrastructure/binance-adapter";
export { PostgresCandleRepository, PostgresSnapshotRepository } from "../infrastructure/postgres-repositories";
export type { MarketDataSqlClient } from "../infrastructure/postgres-repositories";
export { createRedisLatestValueCache, RedisLatestValueCache } from "../infrastructure/redis-latest-value-cache";
export type { RedisLatestValueClient } from "../infrastructure/redis-latest-value-cache";
