"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createMarketDataSnapshotReader = exports.createMarketDataService = exports.shutdown = exports.subscribeMarketData = exports.readDatasetSnapshot = exports.createDatasetSnapshot = exports.readCandles = exports.readPairMetadata = void 0;
const service_1 = require("../application/service");
const defaultService = (0, service_1.createMarketDataService)();
const readPairMetadata = (pair) => defaultService.readPairMetadata(pair);
exports.readPairMetadata = readPairMetadata;
const readCandles = (query) => defaultService.readCandles(query);
exports.readCandles = readCandles;
const createDatasetSnapshot = (command) => defaultService.createDatasetSnapshot(command);
exports.createDatasetSnapshot = createDatasetSnapshot;
const readDatasetSnapshot = (query) => defaultService.readDatasetSnapshot(query);
exports.readDatasetSnapshot = readDatasetSnapshot;
const subscribeMarketData = (subscriptions, sink) => defaultService.subscribeMarketData(subscriptions, sink);
exports.subscribeMarketData = subscribeMarketData;
const shutdown = () => defaultService.shutdown();
exports.shutdown = shutdown;
var service_2 = require("../application/service");
Object.defineProperty(exports, "createMarketDataService", { enumerable: true, get: function () { return service_2.createMarketDataService; } });
var snapshot_reader_1 = require("./snapshot-reader");
Object.defineProperty(exports, "createMarketDataSnapshotReader", { enumerable: true, get: function () { return snapshot_reader_1.createMarketDataSnapshotReader; } });
