"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.reconcileRunningRuns = exports.leaderboard = exports.status = exports.cancel = exports.resume = exports.pause = exports.start = exports.createInMemorySearchDependencies = exports.createSearchModule = void 0;
var service_1 = require("../application/service");
Object.defineProperty(exports, "createSearchModule", { enumerable: true, get: function () { return service_1.createSearchModule; } });
Object.defineProperty(exports, "createInMemorySearchDependencies", { enumerable: true, get: function () { return service_1.createInMemorySearchDependencies; } });
const service_2 = require("../application/service");
const defaultService = (0, service_2.createSearchModule)((0, service_2.createInMemorySearchDependencies)());
const start = (config, options) => defaultService.start(config, options);
exports.start = start;
const pause = (searchRunId, options) => defaultService.pause(searchRunId, options);
exports.pause = pause;
const resume = (searchRunId, options) => defaultService.resume(searchRunId, options);
exports.resume = resume;
const cancel = (searchRunId, options) => defaultService.cancel(searchRunId, options);
exports.cancel = cancel;
const status = (searchRunId, options) => defaultService.status(searchRunId, options);
exports.status = status;
const leaderboard = (searchRunId, options) => defaultService.leaderboard(searchRunId, options);
exports.leaderboard = leaderboard;
const reconcileRunningRuns = () => defaultService.reconcileRunningRuns();
exports.reconcileRunningRuns = reconcileRunningRuns;
