"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.leaderboard = exports.status = exports.cancel = exports.resume = exports.pause = exports.start = exports.createInMemorySearchDependencies = exports.createSearchModule = void 0;
var service_1 = require("../application/service");
Object.defineProperty(exports, "createSearchModule", { enumerable: true, get: function () { return service_1.createSearchModule; } });
Object.defineProperty(exports, "createInMemorySearchDependencies", { enumerable: true, get: function () { return service_1.createInMemorySearchDependencies; } });
const notImplemented = () => { throw new Error("NOT_IMPLEMENTED"); };
const start = async () => notImplemented();
exports.start = start;
const pause = async () => notImplemented();
exports.pause = pause;
const resume = async () => notImplemented();
exports.resume = resume;
const cancel = async () => notImplemented();
exports.cancel = cancel;
const status = async () => notImplemented();
exports.status = status;
const leaderboard = async () => notImplemented();
exports.leaderboard = leaderboard;
