"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.reconcileRunningRuns = exports.leaderboard = exports.status = exports.cancel = exports.resume = exports.pause = exports.start = exports.createInMemorySearchDependencies = exports.createSearchModule = void 0;
var service_1 = require("../application/service");
Object.defineProperty(exports, "createSearchModule", { enumerable: true, get: function () { return service_1.createSearchModule; } });
Object.defineProperty(exports, "createInMemorySearchDependencies", { enumerable: true, get: function () { return service_1.createInMemorySearchDependencies; } });
const service_2 = require("../application/service");
const defaultService = (0, service_2.createSearchModule)((0, service_2.createInMemorySearchDependencies)());
const start = (auth, config) => defaultService.start(auth, config);
exports.start = start;
const pause = (auth, searchRunId) => defaultService.pause(auth, searchRunId);
exports.pause = pause;
const resume = (auth, searchRunId) => defaultService.resume(auth, searchRunId);
exports.resume = resume;
const cancel = (auth, searchRunId) => defaultService.cancel(auth, searchRunId);
exports.cancel = cancel;
const status = (auth, searchRunId) => defaultService.status(auth, searchRunId);
exports.status = status;
const leaderboard = (auth, searchRunId) => defaultService.leaderboard(auth, searchRunId);
exports.leaderboard = leaderboard;
const reconcileRunningRuns = () => defaultService.reconcileRunningRuns();
exports.reconcileRunningRuns = reconcileRunningRuns;
