"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createInMemoryBacktestingDependencies = exports.createBacktestingService = exports.verifyReplay = exports.readExperimentVisualization = exports.listExperimentTrades = exports.scoreExperiment = exports.listSearchExperimentSummaries = exports.readExperimentSummary = exports.listAttemptTrades = exports.readAttempt = exports.removePendingJobs = exports.cancelManualCandidate = exports.cancelSearchCandidates = exports.listSearchCandidates = exports.summarizeSearchCandidates = exports.status = exports.processQueueTerminalSignal = exports.processCompletion = exports.processQueueJob = exports.reconcileCompletions = exports.listQueueRecoveryCandidates = exports.reconcileQueue = exports.submitSearchCandidate = exports.startManual = exports.listBenchmarkScopes = exports.readBenchmarkScope = exports.createBenchmarkScope = exports.simulateBacktest = void 0;
const service_1 = require("../application/service");
var simulator_1 = require("../domain/simulator");
Object.defineProperty(exports, "simulateBacktest", { enumerable: true, get: function () { return simulator_1.simulateBacktest; } });
const defaultService = (0, service_1.createBacktestingService)((0, service_1.createInMemoryBacktestingDependencies)());
const createBenchmarkScope = (auth, command, options) => defaultService.createBenchmarkScope(auth, command, options);
exports.createBenchmarkScope = createBenchmarkScope;
const readBenchmarkScope = (auth, scopeId) => defaultService.readBenchmarkScope(auth, scopeId);
exports.readBenchmarkScope = readBenchmarkScope;
const listBenchmarkScopes = (auth) => defaultService.listBenchmarkScopes(auth);
exports.listBenchmarkScopes = listBenchmarkScopes;
const startManual = (auth, command, options) => defaultService.startManual(auth, command, options);
exports.startManual = startManual;
const submitSearchCandidate = (auth, command) => defaultService.submitSearchCandidate(auth, command);
exports.submitSearchCandidate = submitSearchCandidate;
const reconcileQueue = (limit) => defaultService.reconcileQueue(limit);
exports.reconcileQueue = reconcileQueue;
const listQueueRecoveryCandidates = (limit) => defaultService.listQueueRecoveryCandidates(limit);
exports.listQueueRecoveryCandidates = listQueueRecoveryCandidates;
const reconcileCompletions = (limit) => defaultService.reconcileCompletions(limit);
exports.reconcileCompletions = reconcileCompletions;
const processQueueJob = (job, delivery) => defaultService.processQueueJob(job, delivery);
exports.processQueueJob = processQueueJob;
const processCompletion = (candidateId) => defaultService.processCompletion(candidateId);
exports.processCompletion = processCompletion;
const processQueueTerminalSignal = (signal) => defaultService.processQueueTerminalSignal(signal);
exports.processQueueTerminalSignal = processQueueTerminalSignal;
const status = (auth, candidateId) => defaultService.status(auth, candidateId);
exports.status = status;
const summarizeSearchCandidates = (auth, searchRunId) => defaultService.summarizeSearchCandidates(auth, searchRunId);
exports.summarizeSearchCandidates = summarizeSearchCandidates;
const listSearchCandidates = (auth, searchRunId, page) => defaultService.listSearchCandidates(auth, searchRunId, page);
exports.listSearchCandidates = listSearchCandidates;
const cancelSearchCandidates = (auth, searchRunId, unitOfWork) => defaultService.cancelSearchCandidates(auth, searchRunId, unitOfWork);
exports.cancelSearchCandidates = cancelSearchCandidates;
const cancelManualCandidate = (auth, candidateId) => defaultService.cancelManualCandidate(auth, candidateId);
exports.cancelManualCandidate = cancelManualCandidate;
const removePendingJobs = (candidateIds) => defaultService.removePendingJobs(candidateIds);
exports.removePendingJobs = removePendingJobs;
const readAttempt = (auth, attemptId) => defaultService.readAttempt(auth, attemptId);
exports.readAttempt = readAttempt;
const listAttemptTrades = (auth, attemptId, page) => defaultService.listAttemptTrades(auth, attemptId, page);
exports.listAttemptTrades = listAttemptTrades;
const readExperimentSummary = (auth, experimentId) => defaultService.readExperimentSummary(auth, experimentId);
exports.readExperimentSummary = readExperimentSummary;
const listSearchExperimentSummaries = (auth, searchRunId) => defaultService.listSearchExperimentSummaries(auth, searchRunId);
exports.listSearchExperimentSummaries = listSearchExperimentSummaries;
const scoreExperiment = (auth, experimentId, input) => defaultService.scoreExperiment(auth, experimentId, input);
exports.scoreExperiment = scoreExperiment;
const listExperimentTrades = (auth, experimentId, page) => defaultService.listExperimentTrades(auth, experimentId, page);
exports.listExperimentTrades = listExperimentTrades;
const readExperimentVisualization = (auth, experimentId, page) => defaultService.readExperimentVisualization(auth, experimentId, page);
exports.readExperimentVisualization = readExperimentVisualization;
const verifyReplay = (auth, experimentId) => defaultService.verifyReplay(auth, experimentId);
exports.verifyReplay = verifyReplay;
var service_2 = require("../application/service");
Object.defineProperty(exports, "createBacktestingService", { enumerable: true, get: function () { return service_2.createBacktestingService; } });
Object.defineProperty(exports, "createInMemoryBacktestingDependencies", { enumerable: true, get: function () { return service_2.createInMemoryBacktestingDependencies; } });
