"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.verifyReplay = exports.listExperimentTrades = exports.readExperimentSummary = exports.listAttemptTrades = exports.readAttempt = exports.removePendingJobs = exports.cancelManualCandidate = exports.cancelSearchCandidates = exports.listSearchCandidates = exports.summarizeSearchCandidates = exports.status = exports.submitSearchCandidate = exports.startManual = exports.createBenchmarkScope = exports.simulateBacktest = void 0;
var simulator_1 = require("../domain/simulator");
Object.defineProperty(exports, "simulateBacktest", { enumerable: true, get: function () { return simulator_1.simulateBacktest; } });
const notImplemented = () => { throw new Error("NOT_IMPLEMENTED"); };
const createBenchmarkScope = async () => notImplemented();
exports.createBenchmarkScope = createBenchmarkScope;
const startManual = async () => notImplemented();
exports.startManual = startManual;
const submitSearchCandidate = async () => notImplemented();
exports.submitSearchCandidate = submitSearchCandidate;
const status = async () => notImplemented();
exports.status = status;
const summarizeSearchCandidates = async () => notImplemented();
exports.summarizeSearchCandidates = summarizeSearchCandidates;
const listSearchCandidates = async () => notImplemented();
exports.listSearchCandidates = listSearchCandidates;
const cancelSearchCandidates = async () => notImplemented();
exports.cancelSearchCandidates = cancelSearchCandidates;
const cancelManualCandidate = async () => notImplemented();
exports.cancelManualCandidate = cancelManualCandidate;
const removePendingJobs = async () => notImplemented();
exports.removePendingJobs = removePendingJobs;
const readAttempt = async () => notImplemented();
exports.readAttempt = readAttempt;
const listAttemptTrades = async () => notImplemented();
exports.listAttemptTrades = listAttemptTrades;
const readExperimentSummary = async () => notImplemented();
exports.readExperimentSummary = readExperimentSummary;
const listExperimentTrades = async () => notImplemented();
exports.listExperimentTrades = listExperimentTrades;
const verifyReplay = async () => notImplemented();
exports.verifyReplay = verifyReplay;
