import type { BacktestAttemptAudit, BacktestSubmissionAccepted, BenchmarkScopeSummary, CandidateProgress, CancellationUnitOfWork, CreateLeaderboardScopeCommand, ExperimentResultSummary, ExperimentVisualization, ReplayVerificationResult, StartManualBacktestCommand, SubmitSearchCandidateCommand, Trade } from "../domain/contracts";
import type { BacktestQueueJob, BacktestQueueReturn, BacktestQueueTerminalSignal } from "@cryptox/contracts/queue";
import { createBacktestingService, createInMemoryBacktestingDependencies } from "../application/service";
import type { AuthContext } from "modules/auth/api";
export { simulateBacktest } from "../domain/simulator";
export type { SimulationInput } from "../domain/simulator";
export type { CandidateStatus, BacktestSubmissionAccepted, CancellationUnitOfWork, CompletionUnitOfWork, Trade, CompletedBacktestResult, GeneratorType, CreateLeaderboardScopeCommand, StartManualBacktestCommand, SubmitSearchCandidateCommand, BenchmarkScopeSummary, ReplayVerificationResult, CandidateProgress, BacktestAttemptProgress, BacktestAttemptAudit, ExperimentResult, ExperimentResultSummary, ExperimentVisualization, ExperimentVisualizationMarker } from "../domain/contracts";
export interface SearchCandidateSummary { searchRunId: string; active: CandidateProgress[]; queuedCount: number; runningCount: number; candidatesTested: number; failedCandidateCount: number; retryExhaustedCandidateCount: number; infrastructureFailureCandidateCount: number; completionProcessingFailureCandidateCount: number; failedAttemptCount: number; averageBacktestDurationMs: number | null; }
export interface SearchCandidatePageRequest { limit: number; cursor?: string; }
export interface SearchCandidatePage { items: CandidateProgress[]; nextCursor?: string; }
export interface TradePageRequest { limit: number; cursor?: string; }
export interface TradePage { items: Trade[]; nextCursor?: string; }
export interface ExperimentVisualizationPageRequest { limit: number; cursor?: string; from?: string; to?: string; highlightTradeId?: string; }
export type { AuthContext } from "modules/auth/api";
export interface BacktestLogApi { createBenchmarkScope(auth: AuthContext, command: CreateLeaderboardScopeCommand, options: { scopeIdempotencyKey: string }): Promise<BenchmarkScopeSummary>; readBenchmarkScope(auth: AuthContext, scopeId: string): Promise<BenchmarkScopeSummary>; listBenchmarkScopes(auth: AuthContext): Promise<BenchmarkScopeSummary[]>; startManual(auth: AuthContext, command: StartManualBacktestCommand, options?: { submissionIdempotencyKey?: string }): Promise<BacktestSubmissionAccepted>; submitSearchCandidate(auth: AuthContext, command: SubmitSearchCandidateCommand): Promise<BacktestSubmissionAccepted>; reconcileQueue(limit?: number): Promise<{ dispatched: number; pending: number }>; listQueueRecoveryCandidates(limit?: number): Promise<string[]>; reconcileCompletions(limit?: number): Promise<{ processed: number; pending: number }>; processQueueJob(job: BacktestQueueJob, delivery: { attemptNumber: number; fenceToken?: string }): Promise<BacktestQueueReturn>; processCompletion(candidateId: string): Promise<{ candidateId: string; status: "COMPLETED" | "FAILED" | "IGNORED" }>; processQueueTerminalSignal(signal: BacktestQueueTerminalSignal): Promise<{ candidateId: string; status: "COMPLETED" | "FAILED" | "IGNORED" }>; status(auth: AuthContext, candidateId: string): Promise<CandidateProgress>; summarizeSearchCandidates(auth: AuthContext, searchRunId: string): Promise<SearchCandidateSummary>; listSearchCandidates(auth: AuthContext, searchRunId: string, page: SearchCandidatePageRequest): Promise<SearchCandidatePage>; cancelSearchCandidates(auth: AuthContext, searchRunId: string, unitOfWork: CancellationUnitOfWork): Promise<{ candidateIds: string[] }>; cancelManualCandidate(auth: AuthContext, candidateId: string): Promise<void>; removePendingJobs(candidateIds: string[]): Promise<void>; readAttempt(auth: AuthContext, attemptId: string): Promise<BacktestAttemptAudit>; listAttemptTrades(auth: AuthContext, attemptId: string, page: TradePageRequest): Promise<TradePage>; readExperimentSummary(auth: AuthContext, experimentId: string): Promise<ExperimentResultSummary>; listSearchExperimentSummaries(auth: AuthContext, searchRunId: string): Promise<ExperimentResultSummary[]>; scoreExperiment(auth: AuthContext, experimentId: string, input: { overallScore: number; rankEligible: boolean }): Promise<ExperimentResultSummary>; listExperimentTrades(auth: AuthContext, experimentId: string, page: TradePageRequest): Promise<TradePage>; readExperimentVisualization(auth: AuthContext, experimentId: string, page: ExperimentVisualizationPageRequest): Promise<ExperimentVisualization>; verifyReplay(auth: AuthContext, experimentId: string): Promise<ReplayVerificationResult>; }
const defaultService = createBacktestingService(createInMemoryBacktestingDependencies());
export const createBenchmarkScope: BacktestLogApi["createBenchmarkScope"] = (auth, command, options) => defaultService.createBenchmarkScope(auth, command, options);
export const readBenchmarkScope: BacktestLogApi["readBenchmarkScope"] = (auth, scopeId) => defaultService.readBenchmarkScope(auth, scopeId);
export const listBenchmarkScopes: BacktestLogApi["listBenchmarkScopes"] = (auth) => defaultService.listBenchmarkScopes(auth);
export const startManual: BacktestLogApi["startManual"] = (auth, command, options) => defaultService.startManual(auth, command, options);
export const submitSearchCandidate: BacktestLogApi["submitSearchCandidate"] = (auth, command) => defaultService.submitSearchCandidate(auth, command);
export const reconcileQueue: BacktestLogApi["reconcileQueue"] = (limit) => defaultService.reconcileQueue(limit);
export const listQueueRecoveryCandidates: BacktestLogApi["listQueueRecoveryCandidates"] = (limit) => defaultService.listQueueRecoveryCandidates(limit);
export const reconcileCompletions: BacktestLogApi["reconcileCompletions"] = (limit) => defaultService.reconcileCompletions(limit);
export const processQueueJob: BacktestLogApi["processQueueJob"] = (job, delivery) => defaultService.processQueueJob(job, delivery);
export const processCompletion: BacktestLogApi["processCompletion"] = (candidateId) => defaultService.processCompletion(candidateId);
export const processQueueTerminalSignal: BacktestLogApi["processQueueTerminalSignal"] = (signal) => defaultService.processQueueTerminalSignal(signal);
export const status: BacktestLogApi["status"] = (auth, candidateId) => defaultService.status(auth, candidateId);
export const summarizeSearchCandidates: BacktestLogApi["summarizeSearchCandidates"] = (auth, searchRunId) => defaultService.summarizeSearchCandidates(auth, searchRunId);
export const listSearchCandidates: BacktestLogApi["listSearchCandidates"] = (auth, searchRunId, page) => defaultService.listSearchCandidates(auth, searchRunId, page);
export const cancelSearchCandidates: BacktestLogApi["cancelSearchCandidates"] = (auth, searchRunId, unitOfWork) => defaultService.cancelSearchCandidates(auth, searchRunId, unitOfWork);
export const cancelManualCandidate: BacktestLogApi["cancelManualCandidate"] = (auth, candidateId) => defaultService.cancelManualCandidate(auth, candidateId);
export const removePendingJobs: BacktestLogApi["removePendingJobs"] = (candidateIds) => defaultService.removePendingJobs(candidateIds);
export const readAttempt: BacktestLogApi["readAttempt"] = (auth, attemptId) => defaultService.readAttempt(auth, attemptId);
export const listAttemptTrades: BacktestLogApi["listAttemptTrades"] = (auth, attemptId, page) => defaultService.listAttemptTrades(auth, attemptId, page);
export const readExperimentSummary: BacktestLogApi["readExperimentSummary"] = (auth, experimentId) => defaultService.readExperimentSummary(auth, experimentId);
export const listSearchExperimentSummaries: BacktestLogApi["listSearchExperimentSummaries"] = (auth, searchRunId) => defaultService.listSearchExperimentSummaries(auth, searchRunId);
export const scoreExperiment: BacktestLogApi["scoreExperiment"] = (auth, experimentId, input) => defaultService.scoreExperiment(auth, experimentId, input);
export const listExperimentTrades: BacktestLogApi["listExperimentTrades"] = (auth, experimentId, page) => defaultService.listExperimentTrades(auth, experimentId, page);
export const readExperimentVisualization: BacktestLogApi["readExperimentVisualization"] = (auth, experimentId, page) => defaultService.readExperimentVisualization(auth, experimentId, page);
export const verifyReplay: BacktestLogApi["verifyReplay"] = (auth, experimentId) => defaultService.verifyReplay(auth, experimentId);
export { createBacktestingService, createInMemoryBacktestingDependencies } from "../application/service";
