"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.submit = exports.rankSearchRun = exports.topK = exports.score = exports.DEFAULT_SCORE_FORMULA = exports.createInMemoryLeaderboardDependencies = exports.createLeaderboardModule = void 0;
var service_1 = require("../application/service");
Object.defineProperty(exports, "createLeaderboardModule", { enumerable: true, get: function () { return service_1.createLeaderboardModule; } });
Object.defineProperty(exports, "createInMemoryLeaderboardDependencies", { enumerable: true, get: function () { return service_1.createInMemoryLeaderboardDependencies; } });
Object.defineProperty(exports, "DEFAULT_SCORE_FORMULA", { enumerable: true, get: function () { return service_1.DEFAULT_SCORE_FORMULA; } });
const service_2 = require("../application/service");
const defaultService = (0, service_2.createLeaderboardModule)((0, service_2.createInMemoryLeaderboardDependencies)());
const score = (leaderboardScopeId, metrics) => defaultService.score(leaderboardScopeId, metrics);
exports.score = score;
const topK = (leaderboardScopeId) => defaultService.topK(leaderboardScopeId);
exports.topK = topK;
const rankSearchRun = (searchRunId) => defaultService.rankSearchRun(searchRunId);
exports.rankSearchRun = rankSearchRun;
const submit = (experiment, unitOfWork) => defaultService.submit(experiment, unitOfWork);
exports.submit = submit;
