import React, { useEffect, useMemo, useState } from "react";
import { api, type Composite, type StrategyDefinition, type StrategyDescriptor, type StrategyGenerationResult } from "./api";
import { equalWeights } from "./state";

const Panel = ({ title, children, className = "" }: { title?: string; children: React.ReactNode; className?: string }) => <section className={`panel ${className}`}>{title && <h2>{title}</h2>}{children}</section>;
const Btn = ({ children, primary, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { primary?: boolean }) => <button {...props} className={`btn ${primary ? "primary" : ""}`}>{children}</button>;
const ErrorBox = ({ error }: { error: unknown }) => error ? <p className="error strategy-error" role="alert">{error instanceof Error ? error.message : String(error)}</p> : null;
const Loading = () => <p className="muted" aria-live="polite">Loading live backend data...</p>;
const Empty = ({ children }: { children: React.ReactNode }) => <div className="strategy-empty">{children}</div>;

type Resource<T> = { data?: T; loading: boolean; error?: unknown };
type SourceType = "TEXT" | "URL";

export function strategyDefinitionJson(value: unknown): string { return JSON.stringify(value, null, 2); }
export function weightedComponents(selectedIds: string[], weights: Record<string, number>): Array<{ strategyDefinitionId: string; weight: number }> { const fallback = selectedIds.length ? 1 / selectedIds.length : 0; return selectedIds.map((strategyDefinitionId) => ({ strategyDefinitionId, weight: Number.isFinite(weights[strategyDefinitionId]) ? weights[strategyDefinitionId] : fallback })); }
export function generatedDefinition(result?: StrategyGenerationResult, selected?: StrategyDefinition): StrategyDefinition | undefined { return result?.strategyDefinition ?? selected; }

function useResource<T>(load: () => Promise<T>, refresh: number): Resource<T> {
  const [state, setState] = useState<Resource<T>>({ loading: true });
  useEffect(() => { let active = true; setState({ loading: true }); load().then((data) => active && setState({ data, loading: false })).catch((error) => active && setState({ error, loading: false })); return () => { active = false; }; }, [refresh]);
  return state;
}

function iconFor(name: string): string { return name === "MA" ? "⌁" : name === "RSI" ? "∿" : name === "BOLLINGER" ? "◉" : name === "SUPPORT_RESISTANCE" ? "≋" : "✦"; }
function displayDate(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleString(); }
function parameterSummary(definition?: StrategyDefinition): string { if (!definition) return "No backend definition yet"; const entries = Object.entries(definition.parameters); return entries.length ? entries.map(([key, value]) => `${key}: ${value}`).join(" · ") : "No parameters returned"; }

function StrategyHeader() { return <div className="strategy-header"><div><h1>Create Strategy from Prompt / URL</h1><p>Generate, review, validate, and save definitions returned by the authenticated Strategy backend.</p></div><div className="strategy-header-actions"><span className="strategy-source-pill"><i />Source: Backend API</span><button className="strategy-header-action" aria-label="Help">?</button><button className="strategy-header-action" aria-label="Notifications">♧<i /></button></div></div>; }

function PromptInput({ source, setSource, sourceType, setSourceType, busy, onSubmit, onClear, error }: { source: string; setSource: (value: string) => void; sourceType: SourceType; setSourceType: (value: SourceType) => void; busy: boolean; onSubmit: (event: React.FormEvent) => void; onClear: () => void; error?: unknown }) {
  return <Panel title="Strategy input" className="strategy-input-panel"><div className="strategy-input-tabs"><button className={sourceType === "TEXT" ? "active" : ""} onClick={() => setSourceType("TEXT")} type="button">✦ Prompt</button><button className={sourceType === "URL" ? "active" : ""} onClick={() => setSourceType("URL")} type="button">↗ Website URL</button></div><form onSubmit={onSubmit}><label className="strategy-label">{sourceType === "TEXT" ? "Enter strategy description" : "Enter a public HTTP(S) URL"}{sourceType === "TEXT" ? <textarea required maxLength={4000} value={source} onChange={(event) => setSource(event.target.value)} placeholder="Example: RSI below 30 should produce a long signal. Stop loss 2%, take profit 4%." /> : <input required type="url" pattern="https?://.*" value={source} onChange={(event) => setSource(event.target.value)} placeholder="https://example.com/strategy" />}</label>{sourceType === "TEXT" && <span className="strategy-counter">{source.length}/4000</span>}<div className="strategy-input-actions"><Btn primary disabled={busy || !source.trim()}>{busy ? "Sending to backend..." : sourceType === "TEXT" ? "Analyze with backend" : "Generate from URL"}</Btn><Btn type="button" onClick={onClear}>Clear</Btn></div></form><p className="strategy-contract-note">The public endpoint returns a validated definition. Current adapter: <b>LOCAL_DETERMINISTIC</b>; URL input is validated by the backend and is not presented as fetched web content.</p><ErrorBox error={error} /></Panel>;
}

function ParsedSummary({ definition, result, sourceType }: { definition?: StrategyDefinition; result?: StrategyGenerationResult; sourceType: SourceType }) {
  if (!definition) return <Panel title="Strategy analyzed" className="strategy-summary-panel"><Empty><span className="strategy-empty-icon">⌁</span><b>No generated strategy yet</b><small>Submit a prompt or URL to review the backend-returned definition here.</small></Empty></Panel>;
  return <Panel title="Strategy analyzed" className="strategy-summary-panel"><div className="strategy-summary-identity"><span className="plugin-icon">{iconFor(definition.strategyName)}</span><div><b>{definition.familyName ?? definition.strategyName}</b><small>{definition.strategyName} · version {definition.version}</small></div><span className="strategy-check">✓</span></div><div className="strategy-summary-card green"><b>Backend definition</b><strong>{definition.strategyName}</strong><span>{definition.familyName ?? "Registered strategy plugin"}</span></div><div className="strategy-summary-card purple"><b>Parameters returned</b><span>{parameterSummary(definition)}</span></div><div className="strategy-summary-card blue"><b>Generation source</b><span>{sourceType === "TEXT" ? "Natural language prompt" : "Website URL input"}</span><small>{result?.generationId ?? "Library definition"}</small></div><div className="strategy-summary-card neutral"><b>Signal conditions</b><span>Not exposed by the public Strategy contract.</span><small>The UI does not invent LONG/SHORT rules.</small></div></Panel>;
}

function JsonPreview({ payload }: { payload?: unknown }) { const [message, setMessage] = useState(""); const value = payload === undefined ? "" : strategyDefinitionJson(payload); const copy = async () => { if (!value) return; try { await navigator.clipboard?.writeText(value); setMessage("Copied"); } catch { setMessage("Copy unavailable in this browser"); } }; return <Panel title="Strategy definition (JSON)" className="strategy-json-panel"><div className="strategy-json-toolbar"><span>Actual backend response</span><button type="button" onClick={() => void copy()} disabled={!value}>▣ Copy</button></div>{value ? <pre>{value}</pre> : <Empty><span className="strategy-empty-icon">⌁</span><b>Waiting for backend output</b><small>Generated or selected library data will appear as readable JSON.</small></Empty>}{message && <span className="strategy-copy-message">{message}</span>}</Panel>; }

function ValidationSave({ definition, result, sourceType, descriptors, onRefresh, error, message }: { definition?: StrategyDefinition; result?: StrategyGenerationResult; sourceType: SourceType; descriptors: Resource<StrategyDescriptor[]>; onRefresh: () => void; error?: unknown; message: string }) {
  const supported = definition ? descriptors.data?.some((item) => item.name === definition.strategyName) : false;
  return <Panel title="Validation & save" className="strategy-validation-panel"><div className={`strategy-validation-item ${definition ? "passed" : "waiting"}`}><span>◉</span><div><b>Required definition</b><small>{definition ? "Backend returned a complete definition." : "Waiting for a backend result."}</small></div><strong>{definition ? "✓" : "—"}</strong></div><div className={`strategy-validation-item ${supported ? "passed" : "waiting"}`}><span>⌁</span><div><b>Registered plugin</b><small>{definition ? supported ? "Strategy is present in the loaded plugin catalog." : "Returned strategy is not in the current catalog." : "Validated after generation."}</small></div><strong>{definition && supported ? "✓" : "—"}</strong></div><div className="strategy-validation-status"><b>{definition ? "Valid backend definition" : "No definition to validate"}</b><span>{definition ? "The backend owns validation and persistence." : "Submit input to begin."}</span></div><h3>Save to Strategy Library</h3><label className="strategy-label">Definition ID<input readOnly value={definition?.id ?? "Waiting for generated definition"} /></label><label className="strategy-label">Version<input readOnly value={definition ? `${definition.version} · ${definition.implementationVersion ?? "backend version"}` : "Waiting"} /></label><label className="strategy-label">Source<input readOnly value={definition ? (result ? sourceType === "TEXT" ? "USER_PROMPT · backend persisted" : "WEB_URL · backend persisted" : "GET /strategies/definitions") : "Waiting"} /></label><Btn primary disabled={!definition} onClick={onRefresh}>Refresh persisted library</Btn>{result && <p className="strategy-provenance">Model: <b>{result.modelName ?? "Unavailable"}</b> · Version: {result.modelVersion ?? "Unavailable"} · Prompt: {result.promptVersion ?? "Unavailable"}</p>}{message && <p className="success">{message}</p>}<ErrorBox error={error} /></Panel>;
}

function LibraryTable({ definitions, selected, onSelect, generationId }: { definitions: Resource<StrategyDefinition[]>; selected?: StrategyDefinition; onSelect: (definition: StrategyDefinition) => void; generationId?: string }) {
  return <Panel title="Recent / imported strategies" className="strategy-library-panel"><div className="strategy-library-heading"><span>Persisted rows from <code>GET /strategies/definitions</code></span><span>{definitions.data?.length ?? 0} definitions</span></div>{definitions.loading ? <Loading /> : definitions.error ? <ErrorBox error={definitions.error} /> : definitions.data?.length ? <div className="strategy-table-scroll"><table className="strategy-table"><thead><tr><th>Strategy</th><th>Source</th><th>Created</th><th>Version</th><th>Parameters</th><th>Status</th><th /></tr></thead><tbody>{definitions.data.map((item) => <tr key={item.id} className={selected?.id === item.id ? "selected" : ""}><td><b>{item.familyName ?? item.strategyName}</b><small>{item.strategyName}</small></td><td>{generationId === item.id ? "Current generation" : "Backend library"}</td><td>{displayDate(item.createdAt)}</td><td>v{item.version}</td><td className="strategy-parameters">{parameterSummary(item)}</td><td><span className="strategy-table-status">● Valid</span></td><td><button type="button" className="link-button" onClick={() => onSelect(item)}>Inspect</button></td></tr>)}</tbody></table></div> : <Empty><b>No saved backend definitions yet.</b><small>Generate a strategy or save a plugin definition to populate this library.</small></Empty>}</Panel>;
}

function PluginEditor({ descriptors, onSaved, error, setError }: { descriptors: Resource<StrategyDescriptor[]>; onSaved: () => void; error?: unknown; setError: (error?: unknown) => void }) {
  const [selected, setSelected] = useState<StrategyDescriptor>(); const [parameters, setParameters] = useState<Record<string, number | string>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { if (!selected && descriptors.data?.[0]) { setSelected(descriptors.data[0]); setParameters(Object.fromEntries(descriptors.data[0].parameters.map((item) => [item.key, item.defaultValue]))); } }, [descriptors.data, selected]);
  const select = (item: StrategyDescriptor) => { setSelected(item); setParameters(Object.fromEntries(item.parameters.map((parameter) => [parameter.key, parameter.defaultValue]))); setMessage(""); setError(undefined); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; setBusy(true); setError(undefined); setMessage(""); try { await api.define(selected.name, parameters); setMessage("Definition saved by the backend."); onSaved(); } catch (cause) { setError(cause); } finally { setBusy(false); } };
  return <Panel title="Backend plugin catalog & manual definition" className="strategy-manual-panel"><div className="strategy-plugin-strip">{descriptors.loading ? <Loading /> : descriptors.error ? <ErrorBox error={descriptors.error} /> : descriptors.data?.map((item) => <button type="button" className={`strategy-plugin-card ${selected?.name === item.name ? "selected" : ""}`} key={item.name} onClick={() => select(item)}><span className="plugin-icon">{iconFor(item.name)}</span><span><b>{item.displayName}</b><small>{item.category}</small></span><i>›</i></button>)}</div>{selected ? <form className="strategy-manual-form" onSubmit={(event) => void save(event)}><div><b>{selected.displayName}</b><small>{selected.description}</small></div>{selected.parameters.map((parameter) => <label className="strategy-label" key={parameter.key}>{parameter.label}{parameter.type === "ENUM" && parameter.options ? <select required={parameter.required} value={parameters[parameter.key] ?? ""} onChange={(event) => setParameters({ ...parameters, [parameter.key]: event.target.value })}>{parameter.options.map((option) => <option key={option}>{option}</option>)}</select> : <input type={parameter.type === "NUMBER" ? "number" : "number"} required={parameter.required} value={parameters[parameter.key] ?? ""} min={parameter.minimum} max={parameter.maximum} step={parameter.step} onChange={(event) => setParameters({ ...parameters, [parameter.key]: Number(event.target.value) })} />}</label>)}<Btn primary disabled={busy}>{busy ? "Saving..." : "Save versioned definition"}</Btn></form> : <Empty>Select a loaded backend plugin to edit its parameters.</Empty>}{message && <p className="success">{message}</p>}<ErrorBox error={error} /></Panel>;
}

function CompositeLibrary({ definitions, composites, refresh, error, setError }: { definitions: Resource<StrategyDefinition[]>; composites: Resource<Composite[]>; refresh: () => void; error?: unknown; setError: (error?: unknown) => void }) {
  const [selectedIds, setSelectedIds] = useState<string[]>([]); const [weights, setWeights] = useState<Record<string, number>>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const toggle = (id: string) => { const next = selectedIds.includes(id) ? selectedIds.filter((item) => item !== id) : [...selectedIds, id]; setSelectedIds(next); setWeights(equalWeights(next)); setError(undefined); };
  const save = async () => { if (!selectedIds.length) return; setBusy(true); setError(undefined); setMessage(""); try { await api.defineComposite("WEIGHTED_SCORE", weightedComponents(selectedIds, weights)); setMessage("Weighted composite saved by the backend."); refresh(); } catch (cause) { setError(cause); } finally { setBusy(false); } };
  return <Panel title="Saved library & weighted composites" className="strategy-composite-panel"><div className="strategy-composite-layout"><div><div className="strategy-composite-intro"><b>Build from saved definitions</b><span>Weights are validated by the backend and must sum to 1.</span></div>{definitions.loading || composites.loading ? <Loading /> : definitions.error ? <ErrorBox error={definitions.error} /> : definitions.data?.length ? definitions.data.map((definition) => <label className="strategy-weight-row" key={definition.id}><input type="checkbox" checked={selectedIds.includes(definition.id)} onChange={() => toggle(definition.id)} /><span className="plugin-icon small">{iconFor(definition.strategyName)}</span><span><b>{definition.strategyName} · v{definition.version}</b><small>{definition.id}</small></span><input aria-label={`Weight ${definition.id}`} type="number" min="0" step="0.05" value={weights[definition.id] ?? ""} onChange={(event) => setWeights({ ...weights, [definition.id]: Number(event.target.value) })} /></label>) : <Empty>No saved definitions to combine yet.</Empty>}<p className="muted strategy-weight-total">Selected weight total: {selectedIds.reduce((sum, id) => sum + (weights[id] ?? 0), 0).toFixed(2)} · Backend requires exactly 1.00.</p><Btn primary disabled={busy || !selectedIds.length} onClick={() => void save()}>{busy ? "Saving..." : "Save weighted composite"}</Btn></div><div className="strategy-composites-list"><b>Persisted composites</b>{composites.loading ? <Loading /> : composites.error ? <ErrorBox error={composites.error} /> : composites.data?.length ? composites.data.map((composite) => <article key={composite.id}><div><strong>{composite.method}</strong><small>{composite.components.length} backend components</small></div><span>{composite.components.map((component) => definitions.data?.find((item) => item.id === component.strategyDefinitionId)?.strategyName ?? component.strategyDefinitionId).join(" + ")}</span><code>{composite.id}</code></article>) : <Empty>No saved composites yet.</Empty>}</div></div>{message && <p className="success">{message}</p>}<ErrorBox error={error} /></Panel>;
}

export function StrategyScreen() {
  const [refresh, setRefresh] = useState(0); const descriptors = useResource(api.strategies, refresh); const definitions = useResource(api.definitions, refresh); const composites = useResource(api.composites, refresh); const [sourceType, setSourceType] = useState<SourceType>("TEXT"); const [source, setSource] = useState(""); const [result, setResult] = useState<StrategyGenerationResult>(); const [selected, setSelected] = useState<StrategyDefinition>(); const [generationError, setGenerationError] = useState<unknown>(); const [screenError, setScreenError] = useState<unknown>(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const definition = generatedDefinition(result, selected); const preview = result ?? (selected ? { source: "GET /strategies/definitions", strategyDefinition: selected } : undefined); const refreshLibrary = () => setRefresh((value) => value + 1);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setGenerationError(undefined); setMessage(""); setResult(undefined); try { const generated = await api.generateStrategy(sourceType === "TEXT" ? { sourceType, text: source.trim() } : { sourceType, url: source.trim() }); setResult(generated); setSelected(generated.strategyDefinition); refreshLibrary(); } catch (cause) { setGenerationError(cause); } finally { setBusy(false); } };
  const clear = () => { setSource(""); setResult(undefined); setSelected(undefined); setGenerationError(undefined); setMessage(""); };
  const pluginError = descriptors.error ?? screenError;
  return <div className="strategy-screen"><StrategyHeader /><div className="strategy-workspace"><PromptInput source={source} setSource={setSource} sourceType={sourceType} setSourceType={setSourceType} busy={busy} onSubmit={submit} onClear={clear} error={generationError} /><ParsedSummary definition={definition} result={result} sourceType={sourceType} /><JsonPreview payload={preview} /><ValidationSave definition={definition} result={result} sourceType={sourceType} descriptors={descriptors} onRefresh={refreshLibrary} error={screenError} message={message} /></div><LibraryTable definitions={definitions} selected={selected} onSelect={(item) => { setSelected(item); setResult(undefined); setMessage(""); }} generationId={result?.strategyDefinition?.id} /><PluginEditor descriptors={descriptors} onSaved={() => { setMessage("Definition saved to the backend library."); refreshLibrary(); }} error={pluginError} setError={setScreenError} /><CompositeLibrary definitions={definitions} composites={composites} refresh={refreshLibrary} error={screenError} setError={setScreenError} /></div>;
}
