import React, { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, mapGenerationError, type CombinationMethod, type Composite, type StrategyDefinition, type StrategyDescriptor, type StrategyGenerationResult } from "./api";
import { equalWeights, parameterDefaults } from "./state";

const Panel = ({ title, children, className = "" }: { title?: string; children: React.ReactNode; className?: string }) => <section className={`panel ${className}`}>{title && <h2>{title}</h2>}{children}</section>;
const Btn = ({ children, primary, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { primary?: boolean }) => <button {...props} className={`btn ${primary ? "primary" : ""}`}>{children}</button>;
const ErrorBox = ({ error }: { error: unknown }) => error ? <p className="error strategy-error">{error instanceof Error ? error.message : String(error)}</p> : null;
const Loading = () => <p className="muted">Loading live backend data...</p>;
const Empty = ({ children }: { children: React.ReactNode }) => <div className="strategy-empty">{children}</div>;
type SourceType = "TEXT" | "URL";
type Resource<T> = { data?: T; isLoading: boolean; error: unknown; refetch: () => unknown };

export function strategyDefinitionJson(value: unknown): string { return JSON.stringify(value, null, 2); }
export function weightedComponents(selectedIds: string[], weights: Record<string, number>): Array<{ strategyDefinitionId: string; weight: number }> { const fallback = selectedIds.length ? 1 / selectedIds.length : 0; return selectedIds.map((strategyDefinitionId) => ({ strategyDefinitionId, weight: Number.isFinite(weights[strategyDefinitionId]) ? weights[strategyDefinitionId] : fallback })); }
export function generatedDefinition(result?: StrategyGenerationResult, selected?: StrategyDefinition): StrategyDefinition | undefined { return result?.kind === "SINGLE" ? result.strategyDefinition ?? selected : selected; }
export function generatedComposite(result?: StrategyGenerationResult): Composite | undefined { return result?.kind === "COMPOSITE" ? result.compositeStrategyDefinition : undefined; }

function iconFor(descriptor: Pick<StrategyDescriptor, "category"> | Pick<StrategyDefinition, "strategyName">): string {
  const category = "category" in descriptor ? descriptor.category : descriptor.strategyName;
  return category === "MOMENTUM" ? "∿" : category === "VOLATILITY" ? "◉" : category === "STRUCTURE" ? "≋" : category === "TREND" ? "⌁" : "✦";
}
function displayDate(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleString(); }
function parameterSummary(definition?: StrategyDefinition): string { if (!definition) return "No backend definition yet"; const entries = Object.entries(definition.parameters); return entries.length ? entries.map(([key, value]) => `${key}: ${value}`).join(" · ") : "No parameters returned"; }

function StrategyHeader() { return <div className="strategy-header"><div><h1>Create Strategy from Prompt / URL</h1><p>Generate, review, validate, and save definitions returned by the authenticated Strategy backend.</p></div><div className="strategy-header-actions"><span className="strategy-source-pill"><i />Source: Backend API</span></div></div>; }

function GenerationError({ error }: { error: unknown }) {
  if (!error) return null;
  const mapped = mapGenerationError(error);
  const label = mapped.kind === "SOURCE" ? "Source loading" : mapped.kind === "MODEL" ? "Model unavailable" : mapped.kind === "SCHEMA" ? "Invalid model output" : mapped.kind === "VALIDATION" ? "Strategy validation" : "Generation error";
  return <div className="strategy-error" role="alert"><b>{label}</b><span>{mapped.message}</span></div>;
}

function PromptInput({ source, setSource, sourceType, setSourceType, busy, onSubmit, onClear, error }: { source: string; setSource: (value: string) => void; sourceType: SourceType; setSourceType: (value: SourceType) => void; busy: boolean; onSubmit: (event: React.FormEvent) => void; onClear: () => void; error?: unknown }) {
  return <Panel title="Strategy input" className="strategy-input-panel"><div className="strategy-input-tabs"><button className={sourceType === "TEXT" ? "active" : ""} onClick={() => setSourceType("TEXT")} type="button">✦ Prompt</button><button className={sourceType === "URL" ? "active" : ""} onClick={() => setSourceType("URL")} type="button">↗ Website URL</button></div><form onSubmit={onSubmit}><label className="strategy-label">{sourceType === "TEXT" ? "Enter strategy description" : "Enter a public HTTP(S) URL"}{sourceType === "TEXT" ? <textarea required maxLength={4000} value={source} onChange={(event) => setSource(event.target.value)} placeholder="Example: RSI below 30 should produce a long signal. Stop loss 2%, take profit 4%." /> : <input required type="url" pattern="https?://.*" value={source} onChange={(event) => setSource(event.target.value)} placeholder="https://example.com/strategy" />}</label>{sourceType === "TEXT" && <span className="strategy-counter">{source.length}/4000</span>}<div className="strategy-input-actions"><Btn primary disabled={busy || !source.trim()}>{busy ? "Sending to backend..." : sourceType === "TEXT" ? "Analyze with backend" : "Generate from URL"}</Btn><Btn type="button" onClick={onClear}>Clear</Btn></div></form><p className="strategy-contract-note">The backend returns a persisted SINGLE or COMPOSITE definition. The Frontend never fetches the submitted URL or executes model output.</p><GenerationError error={error} /></Panel>;
}

function ParsedSummary({ definition, composite, result, sourceType }: { definition?: StrategyDefinition; composite?: Composite; result?: StrategyGenerationResult; sourceType: SourceType }) {
  if (!definition && !composite) return <Panel title="Strategy analyzed" className="strategy-summary-panel"><Empty><span className="strategy-empty-icon">⌁</span><b>No generated strategy yet</b><small>Submit a prompt or URL to review the persisted backend result here.</small></Empty></Panel>;
  if (composite) return <Panel title="Strategy analyzed" className="strategy-summary-panel"><div className="strategy-summary-identity"><span className="plugin-icon">✦</span><div><b>Composite strategy</b><small>{composite.method} · version {composite.version}</small></div><span className="strategy-check">✓</span></div><div className="strategy-summary-card green"><b>Backend composite</b><strong>{composite.method}</strong><span>{composite.components.length} persisted components</span></div><div className="strategy-summary-card purple"><b>Combination configuration</b><span>{composite.components.map((component) => `${component.strategyDefinitionId} (${component.weight})`).join(" · ")}</span>{composite.thresholds && <small>Buy ≥ {composite.thresholds.buy} · Sell ≤ {composite.thresholds.sell}</small>}</div><div className="strategy-summary-card blue"><b>Generation source</b><span>{sourceType === "TEXT" ? "Natural language prompt" : "Website URL input"}</span><small>{result?.generationId ?? "Persisted library composite"}</small></div></Panel>;
  return <Panel title="Strategy analyzed" className="strategy-summary-panel"><div className="strategy-summary-identity"><span className="plugin-icon">{iconFor(definition!)}</span><div><b>{definition!.familyName ?? definition!.strategyName}</b><small>{definition!.strategyName} · version {definition!.version}</small></div><span className="strategy-check">✓</span></div><div className="strategy-summary-card green"><b>Backend definition</b><strong>{definition!.strategyName}</strong><span>{definition!.familyName ?? "Registered strategy plugin"}</span></div><div className="strategy-summary-card purple"><b>Parameters returned</b><span>{parameterSummary(definition)}</span></div><div className="strategy-summary-card blue"><b>Generation source</b><span>{sourceType === "TEXT" ? "Natural language prompt" : "Website URL input"}</span><small>{result?.generationId ?? "Persisted library definition"}</small></div></Panel>;
}

function JsonPreview({ payload }: { payload?: unknown }) { const [message, setMessage] = useState(""); const value = payload === undefined ? "" : strategyDefinitionJson(payload); const copy = async () => { if (!value) return; try { await navigator.clipboard?.writeText(value); setMessage("Copied"); } catch { setMessage("Copy unavailable in this browser"); } }; return <Panel title="Strategy definition (JSON)" className="strategy-json-panel"><div className="strategy-json-toolbar"><span>Actual backend response</span><button type="button" onClick={() => void copy()} disabled={!value}>▣ Copy</button></div>{value ? <pre>{value}</pre> : <Empty><span className="strategy-empty-icon">⌁</span><b>Waiting for backend output</b><small>Generated or selected library data will appear as readable JSON.</small></Empty>}{message && <span className="strategy-copy-message">{message}</span>}</Panel>; }

function ValidationSave({ definition, result, sourceType, descriptors, onRefresh, error, message }: { definition?: StrategyDefinition; result?: StrategyGenerationResult; sourceType: SourceType; descriptors: Resource<StrategyDescriptor[]>; onRefresh: () => void; error?: unknown; message: string }) {
  const supported = definition ? descriptors.data?.some((item) => item.name === definition.strategyName) : false;
  return <Panel title="Validation & save" className="strategy-validation-panel"><div className={`strategy-validation-item ${definition ? "passed" : "waiting"}`}><span>◉</span><div><b>Required definition</b><small>{definition ? "Backend returned a complete definition." : "Waiting for a backend result."}</small></div><strong>{definition ? "✓" : "—"}</strong></div><div className={`strategy-validation-item ${supported ? "passed" : "waiting"}`}><span>⌁</span><div><b>Registered plugin</b><small>{definition ? supported ? "Strategy is present in the loaded plugin catalog." : "Returned strategy is not in the current catalog." : "Validated after generation."}</small></div><strong>{definition && supported ? "✓" : "—"}</strong></div><div className="strategy-validation-status"><b>{definition ? "Valid backend definition" : "No single definition to validate"}</b><span>{definition ? "The backend owns validation and persistence." : "Composite results are reviewed in the panel beside this one."}</span></div><h3>Persisted result</h3><label className="strategy-label">Definition ID<input readOnly value={definition?.id ?? result?.compositeStrategyDefinition?.id ?? "Waiting for generated result"} /></label><label className="strategy-label">Version<input readOnly value={definition ? `${definition.version} · ${definition.implementationVersion}` : result?.compositeStrategyDefinition ? `${result.compositeStrategyDefinition.version} · composite` : "Waiting"} /></label><label className="strategy-label">Source<input readOnly value={result ? sourceType === "TEXT" ? "USER_PROMPT · backend persisted" : "WEB_URL · backend persisted" : "GET /strategies/definitions"} /></label><Btn primary disabled={!definition} onClick={onRefresh}>Refresh persisted library</Btn>{result && <p className="strategy-provenance">Model: <b>{result.modelName ?? "Unavailable"}</b> · Version: {result.modelVersion ?? "Unavailable"} · Prompt: {result.promptVersion ?? "Unavailable"}</p>}{message && <p className="success">{message}</p>}<ErrorBox error={error} /></Panel>;
}

function LibraryTable({ definitions, selected, onSelect, generationId }: { definitions: Resource<StrategyDefinition[]>; selected?: StrategyDefinition; onSelect: (definition: StrategyDefinition) => void; generationId?: string }) {
  return <Panel title="Recent / imported strategies" className="strategy-library-panel"><div className="strategy-library-heading"><span>Persisted rows from <code>GET /strategies/definitions</code></span><span>{definitions.data?.length ?? 0} definitions</span></div>{definitions.isLoading ? <Loading /> : definitions.error ? <ErrorBox error={definitions.error} /> : definitions.data?.length ? <div className="strategy-table-scroll"><table className="strategy-table"><thead><tr><th>Strategy</th><th>Source</th><th>Created</th><th>Version</th><th>Parameters</th><th>Status</th><th /></tr></thead><tbody>{definitions.data.map((item) => <tr key={item.id} className={selected?.id === item.id ? "selected" : ""}><td><b>{item.familyName ?? item.strategyName}</b><small>{item.strategyName}</small></td><td>{generationId === item.id ? "Current generation" : "Backend library"}</td><td>{displayDate(item.createdAt)}</td><td>v{item.version}</td><td className="strategy-parameters">{parameterSummary(item)}</td><td><span className="strategy-table-status">● Valid</span></td><td><button type="button" className="link-button" onClick={() => onSelect(item)}>Inspect</button></td></tr>)}</tbody></table></div> : <Empty><b>No saved backend definitions yet.</b><small>Generate a strategy or save a plugin definition to populate this library.</small></Empty>}</Panel>;
}

function PluginEditor({ descriptors, onSaved, error, setError }: { descriptors: Resource<StrategyDescriptor[]>; onSaved: () => void; error?: unknown; setError: (error?: unknown) => void }) {
  const [selected, setSelected] = useState<StrategyDescriptor>(); const [parameters, setParameters] = useState<Record<string, number | string>>({});
  const save = useMutation({ mutationFn: () => selected ? api.define(selected.name, parameters) : Promise.reject(new Error("Select a strategy plugin.")), onSuccess: onSaved, onError: setError });
  useEffect(() => { if (!selected && descriptors.data?.[0]) { setSelected(descriptors.data[0]); setParameters(parameterDefaults(descriptors.data[0].parameters)); } }, [descriptors.data, selected]);
  const select = (item: StrategyDescriptor) => { setSelected(item); setParameters(parameterDefaults(item.parameters)); setError(undefined); };
  return <Panel title="Backend plugin catalog & manual definition" className="strategy-manual-panel"><div className="strategy-plugin-strip">{descriptors.isLoading ? <Loading /> : descriptors.error ? <ErrorBox error={descriptors.error} /> : descriptors.data?.map((item) => <button type="button" className={`strategy-plugin-card ${selected?.name === item.name ? "selected" : ""}`} key={item.name} onClick={() => select(item)}><span className="plugin-icon">{iconFor(item)}</span><span><b>{item.displayName}</b><small>{item.category} · history {item.minimumHistoryCandles}</small></span><i>›</i></button>)}</div>{selected ? <form className="strategy-manual-form" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><div><b>{selected.displayName}</b><small>{selected.description}</small></div>{selected.parameters.map((parameter) => <label className="strategy-label" key={parameter.key}>{parameter.label}{parameter.type === "ENUM" && parameter.options ? <select required={parameter.required} value={parameters[parameter.key] ?? ""} onChange={(event) => setParameters({ ...parameters, [parameter.key]: event.target.value })}>{parameter.options.map((option) => <option key={option}>{option}</option>)}</select> : <input type="number" required={parameter.required} value={parameters[parameter.key] ?? ""} min={parameter.minimum} max={parameter.maximum} step={parameter.step} onChange={(event) => setParameters({ ...parameters, [parameter.key]: Number(event.target.value) })} />}</label>)}<Btn primary disabled={save.isPending}>{save.isPending ? "Saving..." : "Save versioned definition"}</Btn></form> : <Empty>Select a loaded backend plugin to edit its parameters.</Empty>}{save.isSuccess && <p className="success">Definition saved by the backend.</p>}<ErrorBox error={error ?? save.error} /></Panel>;
}

function CompositeLibrary({ definitions, composites, refresh, error, setError }: { definitions: Resource<StrategyDefinition[]>; composites: Resource<Composite[]>; refresh: () => void; error?: unknown; setError: (error?: unknown) => void }) {
  const [selectedIds, setSelectedIds] = useState<string[]>([]); const [weights, setWeights] = useState<Record<string, number>>({}); const [method, setMethod] = useState<CombinationMethod>("MAJORITY_VOTE"); const [buy, setBuy] = useState("0.5"); const [sell, setSell] = useState("-0.5"); const save = useMutation({ mutationFn: () => api.defineComposite(method, method === "WEIGHTED_SCORE" ? weightedComponents(selectedIds, weights) : selectedIds.map((strategyDefinitionId) => ({ strategyDefinitionId, weight: 1 })), method === "WEIGHTED_SCORE" ? { buy: Number(buy), sell: Number(sell) } : undefined), onSuccess: refresh, onError: setError });
  const toggle = (id: string) => { const next = selectedIds.includes(id) ? selectedIds.filter((item) => item !== id) : [...selectedIds, id]; setSelectedIds(next); setWeights(equalWeights(next)); setError(undefined); };
  const weightSum = Object.values(weightedComponents(selectedIds, weights)).reduce((sum, item) => sum + item.weight, 0); const thresholdsValid = Number.isFinite(Number(buy)) && Number.isFinite(Number(sell)) && Number(buy) > Number(sell); const weightedValid = method === "MAJORITY_VOTE" || (Math.abs(weightSum - 1) < 0.0001 && thresholdsValid);
  return <Panel title="Saved library & composites" className="strategy-composite-panel"><div className="strategy-composite-layout"><div><div className="strategy-composite-intro"><b>Build from saved definitions</b><span>Choose the canonical combination method; the backend remains authoritative for normalization.</span></div><label className="strategy-label">Combination method<select value={method} onChange={(event) => setMethod(event.target.value as CombinationMethod)}><option value="MAJORITY_VOTE">MAJORITY_VOTE</option><option value="WEIGHTED_SCORE">WEIGHTED_SCORE</option></select></label>{method === "WEIGHTED_SCORE" && <div className="toolbar"><label className="field">Buy threshold<input type="number" step="0.01" value={buy} onChange={(event) => setBuy(event.target.value)} /></label><label className="field">Sell threshold<input type="number" step="0.01" value={sell} onChange={(event) => setSell(event.target.value)} /></label></div>}{definitions.isLoading || composites.isLoading ? <Loading /> : definitions.error ? <ErrorBox error={definitions.error} /> : definitions.data?.length ? definitions.data.map((definition) => <label className="strategy-weight-row" key={definition.id}><input type="checkbox" checked={selectedIds.includes(definition.id)} onChange={() => toggle(definition.id)} /><span className="plugin-icon small">{iconFor(definition)}</span><span><b>{definition.strategyName} · v{definition.version}</b><small>{definition.id}</small></span>{method === "WEIGHTED_SCORE" && <input aria-label={`Weight ${definition.id}`} type="number" min="0" max="1" step="0.05" value={weights[definition.id] ?? ""} onChange={(event) => setWeights({ ...weights, [definition.id]: Number(event.target.value) })} />}</label>) : <Empty>No saved definitions to combine yet.</Empty>}<p className="muted">{method === "MAJORITY_VOTE" ? "Weights and thresholds are normalized by the backend for majority voting." : `Weight total: ${weightSum.toFixed(2)} · buy > sell: ${thresholdsValid ? "valid" : "required"}`}</p><Btn primary disabled={save.isPending || !selectedIds.length || !weightedValid} onClick={() => save.mutate()}>{save.isPending ? "Saving..." : `Save ${method} composite`}</Btn></div><div className="strategy-composites-list"><b>Persisted composites</b>{composites.isLoading ? <Loading /> : composites.error ? <ErrorBox error={composites.error} /> : composites.data?.length ? composites.data.map((composite) => <article key={composite.id}><div><strong>{composite.method}</strong><small>{composite.components.length} backend components</small></div><span>{composite.components.map((component) => definitions.data?.find((item) => item.id === component.strategyDefinitionId)?.strategyName ?? component.strategyDefinitionId).join(" + ")}</span><code>{composite.id}</code></article>) : <Empty>No saved composites yet.</Empty>}</div></div>{save.isSuccess && <p className="success">Composite saved by the backend.</p>}<ErrorBox error={error ?? save.error} /></Panel>;
}

export function StrategyScreen() {
  const queryClient = useQueryClient(); const descriptorsQuery = useQuery({ queryKey: ["strategies", "descriptors"], queryFn: api.strategies }); const definitionsQuery = useQuery({ queryKey: ["strategies", "definitions"], queryFn: api.definitions }); const compositesQuery = useQuery({ queryKey: ["strategies", "composites"], queryFn: api.composites }); const descriptors = { ...descriptorsQuery, refetch: descriptorsQuery.refetch } as Resource<StrategyDescriptor[]>; const definitions = { ...definitionsQuery, refetch: definitionsQuery.refetch } as Resource<StrategyDefinition[]>; const composites = { ...compositesQuery, refetch: compositesQuery.refetch } as Resource<Composite[]>;
  const [sourceType, setSourceType] = useState<SourceType>("TEXT"); const [source, setSource] = useState(""); const [result, setResult] = useState<StrategyGenerationResult>(); const [selected, setSelected] = useState<StrategyDefinition>(); const [screenError, setScreenError] = useState<unknown>(); const [message, setMessage] = useState("");
  const generation = useMutation({ mutationFn: (input: { sourceType: "TEXT"; text: string } | { sourceType: "URL"; url: string }) => api.generateStrategy(input), onSuccess: (generated) => { setResult(generated); setSelected(generated.kind === "SINGLE" ? generated.strategyDefinition : undefined); setMessage("Backend persisted the generated result."); void queryClient.invalidateQueries({ queryKey: ["strategies"] }); }, onError: setScreenError });
  const definition = generatedDefinition(result, selected); const composite = generatedComposite(result); const preview = result ?? (selected ? { source: "GET /strategies/definitions", strategyDefinition: selected } : undefined); const refreshLibrary = () => { setMessage("Persisted strategy library refreshed."); void queryClient.invalidateQueries({ queryKey: ["strategies"] }); };
  const submit = (event: React.FormEvent) => { event.preventDefault(); setScreenError(undefined); setMessage(""); generation.mutate(sourceType === "TEXT" ? { sourceType, text: source.trim() } : { sourceType, url: source.trim() }); }; const clear = () => { setSource(""); setResult(undefined); setSelected(undefined); setScreenError(undefined); setMessage(""); };
  return <div className="strategy-screen"><StrategyHeader /><div className="strategy-workspace"><PromptInput source={source} setSource={setSource} sourceType={sourceType} setSourceType={setSourceType} busy={generation.isPending} onSubmit={submit} onClear={clear} error={generation.error ?? screenError} /><ParsedSummary definition={definition} composite={composite} result={result} sourceType={sourceType} /><JsonPreview payload={preview} /><ValidationSave definition={definition} result={result} sourceType={sourceType} descriptors={descriptors} onRefresh={refreshLibrary} error={screenError} message={message} /></div><LibraryTable definitions={definitions} selected={selected} onSelect={(item) => { setSelected(item); setResult(undefined); setMessage(""); }} generationId={result?.strategyDefinition?.id} /><PluginEditor descriptors={descriptors} onSaved={refreshLibrary} error={screenError} setError={setScreenError} /><CompositeLibrary definitions={definitions} composites={composites} refresh={refreshLibrary} error={screenError} setError={setScreenError} /></div>;
}
