import type { EvaluationMetrics } from "modules/evaluation/api";
import type { Candle, DatasetSnapshotRef } from "modules/market-data/api";
import type { BacktestAttemptAudit, BacktestAttemptProgress, CompletedBacktestResult, Trade } from "../domain/contracts";
import type { BacktestingRepository, StoredBenchmarkScope, StoredCandidate, StoredExperiment } from "../application/ports";

export interface BacktestingSqlClient { query<Row>(text: string, values: unknown[]): Promise<{ rows: Row[] }>; }
interface TransactionClient extends BacktestingSqlClient { release(): void; }
interface TransactionPool extends BacktestingSqlClient { connect?(): Promise<TransactionClient>; }

const value = <T>(input: T | string): T => typeof input === "string" ? JSON.parse(input) as T : input;
const date = (input: Date | string): string => new Date(input).toISOString();
const number = (input: number | string): number => typeof input === "number" ? input : Number(input);

interface SnapshotRow { id: string; pair: string; pair_metadata: DatasetSnapshotRef["pairMetadata"] | string; timeframe: DatasetSnapshotRef["timeframe"]; dataset_from: Date | string; dataset_to: Date | string; candle_count: number; sha256: string; created_at: Date | string; }
interface CandleRow { timestamp: Date | string; open: number | string; high: number | string; low: number | string; close: number | string; volume: number | string; is_closed: boolean; }
interface ScopeRow extends SnapshotRow { snapshot_id: string; snapshot_created_at: Date | string; owner_user_id: string; idempotency_key: string; name: string; version: number; sentiment_dataset_snapshot: NonNullable<StoredBenchmarkScope["sentimentDatasetSnapshot"]> | string | null; worker_runtime_version: string; worker_runtime_sha256: string; evaluation_runtime_version: string; evaluation_runtime_sha256: string; initial_capital: number | string; fee_rate_percent: number | string; slippage_bps: number; risk_policy: NonNullable<StoredBenchmarkScope["riskPolicy"]> | string | null; decimal_policy_id: "MVP_DECIMAL_HALF_UP_V1"; evaluation_policy_id: "MVP_EVALUATION_V1"; score_formula_id: string; }
interface CandidateRow { id: string; owner_user_id: string; leaderboard_scope_id: string; search_run_id: string | null; iteration_number: number | null; origin: StoredCandidate["origin"]; selection_mode: "SINGLE" | "COMPOSITE"; status: StoredCandidate["status"]; max_attempts: number; active_attempt_number: number | null; completion_attempt_count: number; completion_max_attempts: number; completion_next_retry_at: Date | string | null; experiment_result_id: string | null; failure_kind: StoredCandidate["failureKind"] | null; failure_code: string | null; last_error: string | null; queue_job_id: string; strategy_definitions: StoredCandidate["strategyDefinitions"] | string; composite_definition: StoredCandidate["compositeDefinition"] | string; created_at: Date | string; updated_at: Date | string; }
interface AttemptRow { id: string; candidate_id: string; queue_job_id: string; attempt_number: number; worker_runtime_version: string; worker_runtime_sha256: string; status: BacktestAttemptAudit["status"]; trade_count: number; audit_only: boolean; failure_category: BacktestAttemptAudit["failureCategory"] | null; failure_code: string | null; error_message: string | null; started_at: Date | string; completed_at: Date | string | null; }
interface TradeRow { id: string; sequence: number; pair: string; settlement_asset: string; backtest_attempt_id: string; signal: Trade["signal"]; entry_time: Date | string; market_entry_price: number | string; entry_price: number | string; stop_loss: number | string | null; take_profit: number | string | null; exit_time: Date | string; market_exit_price: number | string; exit_price: number | string; exit_reason: Trade["exitReason"]; quantity: number | string; notional_entry_value: number | string; equity_before_trade: number | string; equity_after_trade: number | string; gross_profit: number | string; fee_amount: number | string; slippage_bps: number; slippage_amount: number | string; profit: number | string; result_percent: number | string; result: Trade["result"]; }
interface ExperimentRow { id: string; candidate_id: string; backtest_attempt_id: string; leaderboard_scope_id: string; score_formula_id: string; overall_score: number | string; rank_eligible: boolean; metrics: EvaluationMetrics | string; created_at: Date | string; }

const snapshot = (row: SnapshotRow): DatasetSnapshotRef => ({ id: row.id, pair: row.pair, pairMetadata: value<DatasetSnapshotRef["pairMetadata"]>(row.pair_metadata), timeframe: row.timeframe, range: { from: date(row.dataset_from), to: date(row.dataset_to) }, candleCount: row.candle_count, sha256: row.sha256, createdAt: date(row.created_at) });
const candle = (row: CandleRow, metadata: DatasetSnapshotRef): Candle => ({ pair: metadata.pair, timeframe: metadata.timeframe, timestamp: date(row.timestamp), open: number(row.open), high: number(row.high), low: number(row.low), close: number(row.close), volume: number(row.volume), isClosed: row.is_closed });
const scope = (row: ScopeRow): StoredBenchmarkScope => { const datasetSnapshot = { ...snapshot(row), id: row.snapshot_id, createdAt: date(row.snapshot_created_at) }; return { id: row.id, ownerUserId: row.owner_user_id, name: row.name, version: row.version, datasetSnapshot, sentimentDatasetSnapshot: row.sentiment_dataset_snapshot === null ? undefined : value<NonNullable<StoredBenchmarkScope["sentimentDatasetSnapshot"]>>(row.sentiment_dataset_snapshot), workerRuntimeVersion: row.worker_runtime_version, workerRuntimeSha256: row.worker_runtime_sha256, evaluationRuntimeVersion: row.evaluation_runtime_version, evaluationRuntimeSha256: row.evaluation_runtime_sha256, pair: row.pair, timeframe: row.timeframe, datasetRange: { from: date(row.dataset_from), to: date(row.dataset_to) }, datasetSnapshotId: datasetSnapshot.id, datasetSnapshotSha256: row.sha256, initialCapital: number(row.initial_capital), feeRatePercent: number(row.fee_rate_percent), slippageBps: row.slippage_bps, riskPolicy: row.risk_policy === null ? undefined : value<NonNullable<StoredBenchmarkScope["riskPolicy"]>>(row.risk_policy), decimalPolicyId: row.decimal_policy_id, evaluationPolicyId: row.evaluation_policy_id, scoreFormulaId: row.score_formula_id, createdAt: date(row.created_at) }; };
const attempt = (row: AttemptRow): BacktestAttemptAudit => ({ attemptId: row.id, candidateId: row.candidate_id, queueJobId: row.queue_job_id, attemptNumber: row.attempt_number, workerRuntimeVersion: row.worker_runtime_version, workerRuntimeSha256: row.worker_runtime_sha256, status: row.status, tradeCount: row.trade_count, auditOnly: row.audit_only, failureCategory: row.failure_category ?? undefined, failureCode: row.failure_code ?? undefined, errorMessage: row.error_message ?? undefined, startedAt: date(row.started_at), completedAt: row.completed_at === null ? undefined : date(row.completed_at) });
const trade = (row: TradeRow): Trade => ({ id: row.id, sequence: row.sequence, pair: row.pair, settlementAsset: row.settlement_asset, backtestAttemptId: row.backtest_attempt_id, signal: row.signal, entryTime: date(row.entry_time), marketEntryPrice: number(row.market_entry_price), entryPrice: number(row.entry_price), stopLoss: row.stop_loss === null ? null : number(row.stop_loss), takeProfit: row.take_profit === null ? null : number(row.take_profit), exitTime: date(row.exit_time), marketExitPrice: number(row.market_exit_price), exitPrice: number(row.exit_price), exitReason: row.exit_reason, quantity: number(row.quantity), notionalEntryValue: number(row.notional_entry_value), equityBeforeTrade: number(row.equity_before_trade), equityAfterTrade: number(row.equity_after_trade), grossProfit: number(row.gross_profit), feeAmount: number(row.fee_amount), slippageBps: row.slippage_bps, slippageAmount: number(row.slippage_amount), profit: number(row.profit), resultPercent: number(row.result_percent), result: row.result });

export class PostgresBacktestingRepository implements BacktestingRepository {
  constructor(private readonly pool: TransactionPool) {}
  private async transaction<T>(operation: (client: BacktestingSqlClient) => Promise<T>): Promise<T> { if (!this.pool.connect) return operation(this.pool); const client = await this.pool.connect(); try { await client.query("BEGIN", []); const result = await operation(client); await client.query("COMMIT", []); return result; } catch (error) { await client.query("ROLLBACK", []); throw error; } finally { client.release(); } }
  async createInputSnapshot(input: DatasetSnapshotRef, candles: Candle[]): Promise<void> { await this.transaction(async (client) => { await client.query("INSERT INTO backtest_input_snapshots (id, pair, pair_metadata, timeframe, dataset_from, dataset_to, candle_count, sha256, created_at) VALUES ($1, $2, $3::jsonb, $4, $5, $6, $7, $8, $9) ON CONFLICT (id) DO NOTHING", [input.id, input.pair, JSON.stringify(input.pairMetadata), input.timeframe, input.range.from, input.range.to, input.candleCount, input.sha256, input.createdAt]); for (const item of candles) await client.query("INSERT INTO backtest_input_candles (snapshot_id, timestamp, open, high, low, close, volume, is_closed) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT (snapshot_id, timestamp) DO NOTHING", [input.id, item.timestamp, item.open, item.high, item.low, item.close, item.volume, item.isClosed]); }); }
  async readInputSnapshot(snapshotId: string) { const head = await this.pool.query<SnapshotRow>("SELECT id, pair, pair_metadata, timeframe, dataset_from, dataset_to, candle_count, sha256, created_at FROM backtest_input_snapshots WHERE id = $1", [snapshotId]); if (!head.rows[0]) return undefined; const metadata = snapshot(head.rows[0]); const rows = await this.pool.query<CandleRow>("SELECT timestamp, open, high, low, close, volume, is_closed FROM backtest_input_candles WHERE snapshot_id = $1 ORDER BY timestamp ASC", [snapshotId]); return { snapshot: metadata, candles: rows.rows.map((row) => candle(row, metadata)) }; }
  async createScope(input: StoredBenchmarkScope, idempotencyKey: string): Promise<StoredBenchmarkScope> { await this.pool.query("INSERT INTO backtest_benchmark_scopes (id, owner_user_id, idempotency_key, name, version, dataset_snapshot_id, sentiment_dataset_snapshot, worker_runtime_version, worker_runtime_sha256, evaluation_runtime_version, evaluation_runtime_sha256, initial_capital, fee_rate_percent, slippage_bps, risk_policy, decimal_policy_id, evaluation_policy_id, score_formula_id, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9, $10, $11, $12, $13, $14, $15::jsonb, $16, $17, $18, $19)", [input.id, input.ownerUserId, idempotencyKey, input.name, input.version, input.datasetSnapshotId, JSON.stringify(input.sentimentDatasetSnapshot ?? null), input.workerRuntimeVersion, input.workerRuntimeSha256, input.evaluationRuntimeVersion, input.evaluationRuntimeSha256, input.initialCapital, input.feeRatePercent, input.slippageBps, JSON.stringify(input.riskPolicy ?? null), input.decimalPolicyId, input.evaluationPolicyId, input.scoreFormulaId, input.createdAt]); return input; }
  private scopeRows(where: string): string { return `SELECT s.id, s.owner_user_id, s.idempotency_key, s.name, s.version, s.sentiment_dataset_snapshot, s.worker_runtime_version, s.worker_runtime_sha256, s.evaluation_runtime_version, s.evaluation_runtime_sha256, s.initial_capital, s.fee_rate_percent, s.slippage_bps, s.risk_policy, s.decimal_policy_id, s.evaluation_policy_id, s.score_formula_id, s.created_at, i.id AS snapshot_id, i.created_at AS snapshot_created_at, i.pair, i.pair_metadata, i.timeframe, i.dataset_from, i.dataset_to, i.candle_count, i.sha256 FROM backtest_benchmark_scopes s JOIN backtest_input_snapshots i ON i.id = s.dataset_snapshot_id ${where}`; }
  async findScopeByIdempotency(ownerUserId: string, idempotencyKey: string) { const result = await this.pool.query<ScopeRow>(this.scopeRows("WHERE s.owner_user_id = $1 AND s.idempotency_key = $2"), [ownerUserId, idempotencyKey]); return result.rows[0] ? scope(result.rows[0]) : undefined; }
  async readScope(scopeId: string) { const result = await this.pool.query<ScopeRow>(this.scopeRows("WHERE s.id = $1"), [scopeId]); return result.rows[0] ? scope(result.rows[0]) : undefined; }
  private async candidateFrom(row: CandidateRow): Promise<StoredCandidate> { return { candidateId: row.id, ownerUserId: row.owner_user_id, origin: row.origin, selectionMode: row.selection_mode, searchRunId: row.search_run_id ?? undefined, iterationNumber: row.iteration_number ?? undefined, leaderboardScopeId: row.leaderboard_scope_id, status: row.status, attempts: await this.listAttempts(row.id), maxAttempts: row.max_attempts, activeAttemptNumber: row.active_attempt_number ?? undefined, completionAttemptCount: row.completion_attempt_count, completionMaxAttempts: row.completion_max_attempts, completionNextRetryAt: row.completion_next_retry_at === null ? undefined : date(row.completion_next_retry_at), experimentResultId: row.experiment_result_id ?? undefined, failureKind: row.failure_kind ?? undefined, failureCode: row.failure_code ?? undefined, lastError: row.last_error ?? undefined, strategyDefinitions: value<StoredCandidate["strategyDefinitions"]>(row.strategy_definitions), compositeDefinition: value<StoredCandidate["compositeDefinition"]>(row.composite_definition), queueJobId: row.queue_job_id, createdAt: date(row.created_at), updatedAt: date(row.updated_at) }; }
  private candidateSql(where: string): string { return `SELECT id, owner_user_id, leaderboard_scope_id, search_run_id, iteration_number, origin, selection_mode, status, max_attempts, active_attempt_number, completion_attempt_count, completion_max_attempts, completion_next_retry_at, experiment_result_id, failure_kind, failure_code, last_error, queue_job_id, strategy_definitions, composite_definition, created_at, updated_at FROM backtest_candidates ${where}`; }
  async createCandidate(input: StoredCandidate, key?: string): Promise<StoredCandidate> { await this.pool.query("INSERT INTO backtest_candidates (id, owner_user_id, leaderboard_scope_id, search_run_id, iteration_number, origin, selection_mode, status, max_attempts, active_attempt_number, completion_attempt_count, completion_max_attempts, completion_next_retry_at, experiment_result_id, failure_kind, failure_code, last_error, queue_job_id, submission_idempotency_key, strategy_definitions, composite_definition, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20::jsonb, $21::jsonb, $22, $23)", [input.candidateId, input.ownerUserId, input.leaderboardScopeId, input.searchRunId ?? null, input.iterationNumber ?? null, input.origin, input.selectionMode, input.status, input.maxAttempts, input.activeAttemptNumber ?? null, input.completionAttemptCount, input.completionMaxAttempts, input.completionNextRetryAt ?? null, input.experimentResultId ?? null, input.failureKind ?? null, input.failureCode ?? null, input.lastError ?? null, input.queueJobId, key ?? null, JSON.stringify(input.strategyDefinitions), JSON.stringify(input.compositeDefinition), input.createdAt, input.updatedAt]); return input; }
  async findCandidateBySubmission(ownerUserId: string, key: string) { const result = await this.pool.query<CandidateRow>(this.candidateSql("WHERE owner_user_id = $1 AND submission_idempotency_key = $2"), [ownerUserId, key]); return result.rows[0] ? this.candidateFrom(result.rows[0]) : undefined; }
  async readCandidate(candidateId: string) { const result = await this.pool.query<CandidateRow>(this.candidateSql("WHERE id = $1"), [candidateId]); return result.rows[0] ? this.candidateFrom(result.rows[0]) : undefined; }
  async updateCandidate(input: StoredCandidate): Promise<void> { await this.pool.query("UPDATE backtest_candidates SET status = $2, active_attempt_number = $3, completion_attempt_count = $4, completion_max_attempts = $5, completion_next_retry_at = $6, experiment_result_id = $7, failure_kind = $8, failure_code = $9, last_error = $10, updated_at = $11 WHERE id = $1", [input.candidateId, input.status, input.activeAttemptNumber ?? null, input.completionAttemptCount, input.completionMaxAttempts, input.completionNextRetryAt ?? null, input.experimentResultId ?? null, input.failureKind ?? null, input.failureCode ?? null, input.lastError ?? null, input.updatedAt]); }
  async listCandidatesBySearchRun(searchRunId: string) { const result = await this.pool.query<CandidateRow>(this.candidateSql("WHERE search_run_id = $1 ORDER BY created_at ASC"), [searchRunId]); return Promise.all(result.rows.map((row) => this.candidateFrom(row))); }
  async createAttempt(input: BacktestAttemptAudit): Promise<void> { await this.pool.query("INSERT INTO backtest_attempts (id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, failure_category, failure_code, error_message, started_at, completed_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)", [input.attemptId, input.candidateId, input.queueJobId, input.attemptNumber, input.workerRuntimeVersion, input.workerRuntimeSha256, input.status, input.tradeCount, input.auditOnly, input.failureCategory ?? null, input.failureCode ?? null, input.errorMessage ?? null, input.startedAt, input.completedAt ?? null]); }
  async updateAttempt(input: BacktestAttemptAudit): Promise<void> { await this.pool.query("UPDATE backtest_attempts SET status = $2, trade_count = $3, audit_only = $4, failure_category = $5, failure_code = $6, error_message = $7, completed_at = $8 WHERE id = $1", [input.attemptId, input.status, input.tradeCount, input.auditOnly, input.failureCategory ?? null, input.failureCode ?? null, input.errorMessage ?? null, input.completedAt ?? null]); }
  async readAttempt(attemptId: string) { const result = await this.pool.query<AttemptRow>("SELECT id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, failure_category, failure_code, error_message, started_at, completed_at FROM backtest_attempts WHERE id = $1", [attemptId]); return result.rows[0] ? attempt(result.rows[0]) : undefined; }
  async listAttempts(candidateId: string): Promise<BacktestAttemptProgress[]> { const result = await this.pool.query<AttemptRow>("SELECT id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, failure_category, failure_code, error_message, started_at, completed_at FROM backtest_attempts WHERE candidate_id = $1 ORDER BY attempt_number ASC", [candidateId]); return result.rows.map(attempt); }
  private async saveTrade(client: BacktestingSqlClient, item: Trade): Promise<void> { await client.query("INSERT INTO backtest_trades (id, backtest_attempt_id, sequence, pair, settlement_asset, signal, entry_time, market_entry_price, entry_price, stop_loss, take_profit, exit_time, market_exit_price, exit_price, exit_reason, quantity, notional_entry_value, equity_before_trade, equity_after_trade, gross_profit, fee_amount, slippage_bps, slippage_amount, profit, result_percent, result) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)", [item.id, item.backtestAttemptId, item.sequence, item.pair, item.settlementAsset, item.signal, item.entryTime, item.marketEntryPrice, item.entryPrice, item.stopLoss, item.takeProfit, item.exitTime, item.marketExitPrice, item.exitPrice, item.exitReason, item.quantity, item.notionalEntryValue, item.equityBeforeTrade, item.equityAfterTrade, item.grossProfit, item.feeAmount, item.slippageBps, item.slippageAmount, item.profit, item.resultPercent, item.result]); }
  async completeAttempt(input: { candidate: StoredCandidate; attempt: BacktestAttemptAudit; result: CompletedBacktestResult; metrics: EvaluationMetrics; experiment: StoredExperiment }): Promise<void> { await this.transaction(async (client) => { await client.query("UPDATE backtest_attempts SET status = $2, trade_count = $3, completed_at = $4 WHERE id = $1", [input.attempt.attemptId, input.attempt.status, input.attempt.tradeCount, input.attempt.completedAt]); for (const item of input.result.trades) await this.saveTrade(client, item); await client.query("INSERT INTO backtest_experiment_results (id, candidate_id, backtest_attempt_id, leaderboard_scope_id, score_formula_id, overall_score, rank_eligible, metrics, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9)", [input.experiment.id, input.experiment.candidateId, input.experiment.backtestAttemptId, input.experiment.leaderboardScopeId, input.experiment.scoreFormulaId, input.experiment.overallScore, input.experiment.rankEligible, JSON.stringify(input.metrics), input.experiment.createdAt]); await client.query("UPDATE backtest_candidates SET status = $2, active_attempt_number = NULL, completion_attempt_count = $3, experiment_result_id = $4, updated_at = $5 WHERE id = $1", [input.candidate.candidateId, input.candidate.status, input.candidate.completionAttemptCount, input.experiment.id, input.candidate.updatedAt]); }); }
  async listTrades(attemptId: string) { const result = await this.pool.query<TradeRow>("SELECT id, sequence, pair, settlement_asset, backtest_attempt_id, signal, entry_time, market_entry_price, entry_price, stop_loss, take_profit, exit_time, market_exit_price, exit_price, exit_reason, quantity, notional_entry_value, equity_before_trade, equity_after_trade, gross_profit, fee_amount, slippage_bps, slippage_amount, profit, result_percent, result FROM backtest_trades WHERE backtest_attempt_id = $1 ORDER BY sequence ASC", [attemptId]); return result.rows.map(trade); }
  async readExperiment(experimentId: string) { const result = await this.pool.query<ExperimentRow>("SELECT id, candidate_id, backtest_attempt_id, leaderboard_scope_id, score_formula_id, overall_score, rank_eligible, metrics, created_at FROM backtest_experiment_results WHERE id = $1", [experimentId]); return result.rows[0] ? this.experiment(result.rows[0]) : undefined; }
  async findExperimentByCandidate(candidateId: string) { const result = await this.pool.query<ExperimentRow>("SELECT id, candidate_id, backtest_attempt_id, leaderboard_scope_id, score_formula_id, overall_score, rank_eligible, metrics, created_at FROM backtest_experiment_results WHERE candidate_id = $1", [candidateId]); return result.rows[0] ? this.experiment(result.rows[0]) : undefined; }
  async listExperimentsBySearchRun(searchRunId: string) { const result = await this.pool.query<ExperimentRow>("SELECT r.id, r.candidate_id, r.backtest_attempt_id, r.leaderboard_scope_id, r.score_formula_id, r.overall_score, r.rank_eligible, r.metrics, r.created_at FROM backtest_experiment_results r JOIN backtest_candidates c ON c.id = r.candidate_id WHERE c.search_run_id = $1 ORDER BY r.created_at ASC", [searchRunId]); return Promise.all(result.rows.map((row) => this.experiment(row))); }
  async updateExperimentScore(experimentId: string, input: { overallScore: number; rankEligible: boolean }) { const result = await this.pool.query<ExperimentRow>("UPDATE backtest_experiment_results SET overall_score = $2, rank_eligible = $3 WHERE id = $1 RETURNING id, candidate_id, backtest_attempt_id, leaderboard_scope_id, score_formula_id, overall_score, rank_eligible, metrics, created_at", [experimentId, input.overallScore, input.rankEligible]); return result.rows[0] ? this.experiment(result.rows[0]) : undefined; }
  private async experiment(row: ExperimentRow): Promise<StoredExperiment> { const candidate = await this.readCandidate(row.candidate_id); const benchmark = await this.readScope(row.leaderboard_scope_id); if (!candidate || !benchmark) throw new Error("BACKTEST_PERSISTENCE_INTEGRITY_ERROR"); const trades = await this.listTrades(row.backtest_attempt_id); return { id: row.id, ownerUserId: candidate.ownerUserId, candidateId: row.candidate_id, searchRunId: candidate.searchRunId, leaderboardScopeId: row.leaderboard_scope_id, scoreFormulaId: row.score_formula_id, overallScore: number(row.overall_score), rankEligible: row.rank_eligible, backtestAttemptId: row.backtest_attempt_id, compositeDefinitionId: candidate.compositeDefinition.id, compositeDefinition: candidate.compositeDefinition, datasetSnapshot: benchmark.datasetSnapshot, sentimentDatasetSnapshot: benchmark.sentimentDatasetSnapshot, strategyDefinitions: candidate.strategyDefinitions, metrics: value<EvaluationMetrics>(row.metrics), trades, createdAt: date(row.created_at) }; }
}

export const createPostgresBacktestingDependencies = (pool: TransactionPool, dependencies: Omit<import("../application/ports").BacktestingModuleDependencies, "repository">): import("../application/ports").BacktestingModuleDependencies => ({ ...dependencies, repository: new PostgresBacktestingRepository(pool) });
