import type { EvaluationMetrics } from "modules/evaluation/api";
import type { Candle, DatasetSnapshotRef } from "modules/market-data/api";
import { createHash, randomUUID } from "node:crypto";
import { backtestAttemptDurationMs } from "../domain/contracts";
import type { BacktestAttemptAudit, BacktestAttemptProgress, CancellationUnitOfWork, CompletedBacktestResult, CompletionUnitOfWork, ReplayVerificationResult, Trade } from "../domain/contracts";
import type { BacktestDispatch, BacktestingRepository, CompletionProcessingClaim, StoredBenchmarkScope, StoredCandidate, StoredExperiment, StoredReplayVerification, WorkerAttemptClaim } from "../application/ports";
import type { BacktestQueueJob } from "@cryptox/contracts/queue";
import { createEvaluationModule } from "../../evaluation/api/bootstrap";
import { TIMEFRAME_SECONDS, missingRanges, snapshotSerialization } from "../../market-data/api";

export interface BacktestingSqlClient { query<Row>(text: string, values: unknown[]): Promise<{ rows: Row[] }>; }
interface TransactionClient extends BacktestingSqlClient { release(): void; }
interface TransactionPool extends BacktestingSqlClient { connect?(): Promise<TransactionClient>; }

const DEFAULT_WARMUP_CAPACITY_CANDLES = 500;
const RECOVERY_RUNTIME_VERSION = "RECOVERY_SYNTHETIC_V1";
const RECOVERY_RUNTIME_SHA256 = createHash("sha256").update(RECOVERY_RUNTIME_VERSION, "utf8").digest("hex");
const value = <T>(input: T | string): T => typeof input === "string" ? JSON.parse(input) as T : input;
const date = (input: Date | string): string => new Date(input).toISOString();
const number = (input: number | string): number => typeof input === "number" ? input : Number(input);
const positiveNullable = (input: number | string | null | undefined): number | null => {
  if (input === null || input === undefined) return null;
  const parsed = number(input);
  if (!Number.isFinite(parsed) || parsed <= 0) throw new Error("BACKTEST_INVALID_TRADE_RISK_FIELD");
  return parsed;
};
const validateTradeRisk = (trade: Pick<Trade, "stopLoss" | "takeProfit">): void => {
  positiveNullable(trade.stopLoss);
  positiveNullable(trade.takeProfit);
};

const invalidSnapshot = (): never => { throw new Error("BACKTEST_INPUT_SNAPSHOT_INTEGRITY_FAILURE"); };
const validateInputSnapshot = (input: DatasetSnapshotRef, candles: Candle[]): void => {
  const interval = TIMEFRAME_SECONDS[input.timeframe] * 1_000;
  const from = Date.parse(input.range.from);
  const to = Date.parse(input.range.to);
  if (!input.id || !Number.isFinite(from) || !Number.isFinite(to) || to <= from || !Number.isInteger(input.candleCount) || input.candleCount <= 0 || input.candleCount !== candles.length || !/^[a-f0-9]{64}$/i.test(input.sha256)) invalidSnapshot();
  if (candles.some((item, index) => !item.isClosed || item.pair !== input.pair || item.timeframe !== input.timeframe || !Number.isFinite(Date.parse(item.timestamp)) || (index > 0 && Date.parse(item.timestamp) <= Date.parse(candles[index - 1]!.timestamp))) || new Set(candles.map((item) => item.timestamp)).size !== candles.length) invalidSnapshot();
  if (candles[0]!.timestamp !== input.range.from || candles.at(-1)!.timestamp !== new Date(to - interval).toISOString() || missingRanges(candles, input.range, input.timeframe).length > 0) invalidSnapshot();
  const expectedHash = createHash("sha256").update(snapshotSerialization(input.pair, input.timeframe, input.range, candles), "utf8").digest("hex");
  if (expectedHash !== input.sha256) invalidSnapshot();
};

interface SnapshotRow { id: string; pair: string; pair_metadata: DatasetSnapshotRef["pairMetadata"] | string; timeframe: DatasetSnapshotRef["timeframe"]; dataset_from: Date | string; dataset_to: Date | string; candle_count: number; sha256: string; created_at: Date | string; }
interface CandleRow { timestamp: Date | string; open: number | string; high: number | string; low: number | string; close: number | string; volume: number | string; is_closed: boolean; }
interface ScopeRow extends SnapshotRow { snapshot_id: string; snapshot_created_at: Date | string; owner_user_id: string; idempotency_key: string; name: string; version: number; sentiment_dataset_snapshot: NonNullable<StoredBenchmarkScope["sentimentDatasetSnapshot"]> | string | null; worker_runtime_version: string; worker_runtime_sha256: string; evaluation_runtime_version: string; evaluation_runtime_sha256: string; simulator_version?: string; simulator_sha256?: string; benchmark_timezone?: string; fill_policy_id?: string; opposite_signal_policy_id?: string; same_candle_ordering_policy_id?: string; deterministic_guarantee?: string; initial_capital: number | string; fee_rate_percent: number | string; slippage_bps: number; warmup_capacity_candles: number; risk_policy: NonNullable<StoredBenchmarkScope["riskPolicy"]> | string | null; decimal_policy_id: "MVP_DECIMAL_HALF_UP_V1"; evaluation_policy_id: "MVP_EVALUATION_V1"; score_formula_id: string; }
interface CandidateRow { id: string; owner_user_id: string; leaderboard_scope_id: string; search_run_id: string | null; iteration_number: number | null; generated_by: StoredCandidate["generatedBy"] | null; fingerprint: string | null; lineage: StoredCandidate["lineage"] | string | null; origin: StoredCandidate["origin"]; selection_mode: "SINGLE" | "COMPOSITE"; status: StoredCandidate["status"]; max_attempts: number; active_attempt_number: number | null; completion_attempt_count: number; completion_max_attempts: number; completion_next_retry_at: Date | string | null; completion_generation: number; active_completion_claim_token: string | null; active_completion_lease_expires_at: Date | string | null; experiment_result_id: string | null; failure_kind: StoredCandidate["failureKind"] | null; failure_code: string | null; last_error: string | null; queue_job_id: string; execution_generation: number; active_fence_token: string | null; active_lease_expires_at: Date | string | null; warmup_candles: number; execution_policy?: StoredCandidate["executionPolicy"] | string | null; strategy_definitions: StoredCandidate["strategyDefinitions"] | string; composite_definition: StoredCandidate["compositeDefinition"] | string; created_at: Date | string; updated_at: Date | string; }
interface AttemptRow { id: string; candidate_id: string; queue_job_id: string; attempt_number: number; worker_runtime_version: string; worker_runtime_sha256: string; status: BacktestAttemptAudit["status"]; trade_count: number; audit_only: boolean; delivery_attempt_count: number; fence_token: string | null; lease_expires_at: Date | string | null; failure_category: BacktestAttemptAudit["failureCategory"] | null; failure_code: string | null; error_message: string | null; started_at: Date | string; completed_at: Date | string | null; }
interface DispatchRow { job_id: string; payload: BacktestQueueJob | string; state: BacktestDispatch["state"]; dispatch_attempts: number; last_error: string | null; dispatched_at: Date | string | null; created_at: Date | string; updated_at: Date | string; }
interface TradeRow { id: string; sequence: number; pair: string; settlement_asset: string; backtest_attempt_id: string; signal: Trade["signal"]; entry_time: Date | string; market_entry_price: number | string; entry_price: number | string; stop_loss: number | string | null; take_profit: number | string | null; exit_time: Date | string; market_exit_price: number | string; exit_price: number | string; exit_reason: Trade["exitReason"]; quantity: number | string; notional_entry_value: number | string; equity_before_trade: number | string; equity_after_trade: number | string; gross_profit: number | string; fee_amount: number | string; slippage_bps: number; slippage_amount: number | string; profit: number | string; result_percent: number | string; result: Trade["result"]; }
interface ExperimentRow { id: string; candidate_id: string; backtest_attempt_id: string; leaderboard_scope_id: string; score_formula_id: string; overall_score: number | string; rank_eligible: boolean; metrics: EvaluationMetrics | string; created_at: Date | string; }
interface ReplayRow { id: string; owner_user_id: string; experiment_result_id: string; status: StoredReplayVerification["status"]; mismatch_sample_limit: number; compared_trade_count: number | null; mismatch_sample: Array<{ fieldPath: string; expected: string; actual: string }> | string | null; total_mismatch_count: number | null; truncated: boolean | null; failure_code: Extract<ReplayVerificationResult, { status: "NON_REPLAYABLE" }>["failureCode"] | null; claim_token: string | null; lease_expires_at: Date | string | null; created_at: Date | string; started_at: Date | string | null; completed_at: Date | string | null; backtest_attempt_id?: string; }

const snapshot = (row: SnapshotRow): DatasetSnapshotRef => ({ id: row.id, pair: row.pair, pairMetadata: value<DatasetSnapshotRef["pairMetadata"]>(row.pair_metadata), timeframe: row.timeframe, range: { from: date(row.dataset_from), to: date(row.dataset_to) }, candleCount: row.candle_count, sha256: row.sha256, createdAt: date(row.created_at) });
const candle = (row: CandleRow, metadata: DatasetSnapshotRef): Candle => ({ pair: metadata.pair, timeframe: metadata.timeframe, timestamp: date(row.timestamp), open: number(row.open), high: number(row.high), low: number(row.low), close: number(row.close), volume: number(row.volume), isClosed: row.is_closed });
const scope = (row: ScopeRow): StoredBenchmarkScope => { const datasetSnapshot = { ...snapshot(row), id: row.snapshot_id, createdAt: date(row.snapshot_created_at) }; return { id: row.id, ownerUserId: row.owner_user_id, name: row.name, version: row.version, datasetSnapshot, sentimentDatasetSnapshot: row.sentiment_dataset_snapshot === null ? undefined : value<NonNullable<StoredBenchmarkScope["sentimentDatasetSnapshot"]>>(row.sentiment_dataset_snapshot), workerRuntimeVersion: row.worker_runtime_version, workerRuntimeSha256: row.worker_runtime_sha256, evaluationRuntimeVersion: row.evaluation_runtime_version, evaluationRuntimeSha256: row.evaluation_runtime_sha256, simulatorVersion: row.simulator_version ?? "1.0.0", simulatorSha256: row.simulator_sha256 ?? "2ed4a4326ba78169d9432c10f05272b01c53a5518ead8ab873be35bd2f1305bf", benchmarkTimezone: row.benchmark_timezone ?? "UTC", fillPolicyId: row.fill_policy_id ?? "NEXT_OPEN_OHLC_STOP_FIRST_V2", oppositeSignalPolicyId: row.opposite_signal_policy_id ?? "CLOSE_AND_REVERSE_NEXT_OPEN_V1", sameCandleOrderingPolicyId: row.same_candle_ordering_policy_id ?? "ENTRY_THEN_PROTECTIVE_EXIT_THEN_CLOSE_V1", deterministicGuarantee: row.deterministic_guarantee ?? "SEALED_INPUTS_AND_RETAINED_ARTIFACTS", pair: row.pair, timeframe: row.timeframe, datasetRange: { from: date(row.dataset_from), to: date(row.dataset_to) }, datasetSnapshotId: datasetSnapshot.id, datasetSnapshotSha256: row.sha256, warmupCapacityCandles: row.warmup_capacity_candles, initialCapital: number(row.initial_capital), feeRatePercent: number(row.fee_rate_percent), slippageBps: row.slippage_bps, riskPolicy: row.risk_policy === null ? undefined : value<NonNullable<StoredBenchmarkScope["riskPolicy"]>>(row.risk_policy), decimalPolicyId: row.decimal_policy_id, evaluationPolicyId: row.evaluation_policy_id, scoreFormulaId: row.score_formula_id, createdAt: date(row.created_at) }; };
const attempt = (row: AttemptRow): BacktestAttemptAudit => { const startedAt = date(row.started_at)!; const completedAt = row.completed_at === null ? undefined : date(row.completed_at); return { attemptId: row.id, candidateId: row.candidate_id, queueJobId: row.queue_job_id, attemptNumber: row.attempt_number, workerRuntimeVersion: row.worker_runtime_version, workerRuntimeSha256: row.worker_runtime_sha256, status: row.status, tradeCount: row.trade_count, auditOnly: row.audit_only, deliveryAttemptCount: row.delivery_attempt_count, fenceToken: row.fence_token ?? undefined, leaseExpiresAt: row.lease_expires_at === null ? undefined : date(row.lease_expires_at), failureCategory: row.failure_category ?? undefined, failureCode: row.failure_code ?? undefined, errorMessage: row.error_message ?? undefined, startedAt, completedAt, durationMs: backtestAttemptDurationMs(startedAt, completedAt) }; };
const dispatch = (row: DispatchRow): BacktestDispatch => ({ job: value<BacktestQueueJob>(row.payload), state: row.state, dispatchAttempts: row.dispatch_attempts, lastError: row.last_error ?? undefined, dispatchedAt: row.dispatched_at === null ? undefined : date(row.dispatched_at), createdAt: date(row.created_at), updatedAt: date(row.updated_at) });
const trade = (row: TradeRow): Trade => ({ id: row.id, sequence: row.sequence, pair: row.pair, settlementAsset: row.settlement_asset, backtestAttemptId: row.backtest_attempt_id, signal: row.signal, entryTime: date(row.entry_time), marketEntryPrice: number(row.market_entry_price), entryPrice: number(row.entry_price), stopLoss: positiveNullable(row.stop_loss), takeProfit: positiveNullable(row.take_profit), exitTime: date(row.exit_time), marketExitPrice: number(row.market_exit_price), exitPrice: number(row.exit_price), exitReason: row.exit_reason, quantity: number(row.quantity), notionalEntryValue: number(row.notional_entry_value), equityBeforeTrade: number(row.equity_before_trade), equityAfterTrade: number(row.equity_after_trade), grossProfit: number(row.gross_profit), feeAmount: number(row.fee_amount), slippageBps: row.slippage_bps, slippageAmount: number(row.slippage_amount), profit: number(row.profit), resultPercent: number(row.result_percent), result: row.result });
const projectAmounts = (initialCapital: number, trades: Trade[]): Pick<StoredExperiment, "initialCapital" | "totalProfitAmount" | "endingEquity" | "wins" | "losses" | "breakevens" | "maxDrawdownAmount"> => { let totalProfitAmount = 0; let peak = initialCapital; let maxDrawdownAmount = 0; let wins = 0; let losses = 0; let breakevens = 0; for (const item of trades) { totalProfitAmount += item.profit; peak = Math.max(peak, item.equityAfterTrade); maxDrawdownAmount = Math.max(maxDrawdownAmount, peak - item.equityAfterTrade); if (item.result === "WIN") wins += 1; else if (item.result === "LOSS") losses += 1; else breakevens += 1; } return { initialCapital: Number(initialCapital.toFixed(2)), totalProfitAmount: Number(totalProfitAmount.toFixed(2)), endingEquity: Number((initialCapital + totalProfitAmount).toFixed(2)), wins, losses, breakevens, maxDrawdownAmount: Number(maxDrawdownAmount.toFixed(2)) }; };
const replay = (row: ReplayRow): StoredReplayVerification => {
  if (!row.backtest_attempt_id) throw new Error("BACKTEST_PERSISTENCE_INTEGRITY_ERROR");
  const base = { replayJobId: row.id, experimentId: row.experiment_result_id, sourceAttemptId: row.backtest_attempt_id, ownerUserId: row.owner_user_id, mismatchSampleLimit: row.mismatch_sample_limit, requestedAt: date(row.created_at), startedAt: row.started_at === null ? undefined : date(row.started_at), completedAt: row.completed_at === null ? undefined : date(row.completed_at), activeClaimToken: row.claim_token ?? undefined, leaseExpiresAt: row.lease_expires_at === null ? undefined : date(row.lease_expires_at) };
  if (row.status === "QUEUED" || row.status === "RUNNING") return { ...base, status: row.status };
  if (row.status === "NON_REPLAYABLE" && row.failure_code) return { ...base, status: row.status, failureCode: row.failure_code };
  if (row.status === "MATCH" && row.compared_trade_count !== null && row.total_mismatch_count !== null && row.truncated !== null) return { ...base, status: "MATCH", comparedTradeCount: row.compared_trade_count, mismatches: [], totalMismatchCount: 0, truncated: false };
  if (row.status === "MISMATCH" && row.compared_trade_count !== null && row.total_mismatch_count !== null && row.truncated !== null) return { ...base, status: "MISMATCH", comparedTradeCount: row.compared_trade_count, mismatches: row.mismatch_sample === null ? [] : value<Array<{ fieldPath: string; expected: string; actual: string }>>(row.mismatch_sample), totalMismatchCount: row.total_mismatch_count, truncated: row.truncated };
  throw new Error("BACKTEST_PERSISTENCE_INTEGRITY_ERROR");
};

export class PostgresBacktestingRepository implements BacktestingRepository {
  constructor(private readonly pool: TransactionPool) {}
  private async transaction<T>(operation: (client: BacktestingSqlClient) => Promise<T>): Promise<T> { if (!this.pool.connect) return operation(this.pool); const client = await this.pool.connect(); try { await client.query("BEGIN", []); const result = await operation(client); await client.query("COMMIT", []); return result; } catch (error) { await client.query("ROLLBACK", []); throw error; } finally { client.release(); } }
  async createInputSnapshot(input: DatasetSnapshotRef, candles: Candle[]): Promise<DatasetSnapshotRef> { validateInputSnapshot(input, candles); return this.transaction(async (client) => { const existing = await client.query<SnapshotRow>("SELECT id, pair, pair_metadata, timeframe, dataset_from, dataset_to, candle_count, sha256, created_at FROM backtest_input_snapshots WHERE sha256 = $1 FOR UPDATE", [input.sha256]); if (existing.rows[0]) { const saved = snapshot(existing.rows[0]); const rows = await client.query<CandleRow>("SELECT timestamp, open, high, low, close, volume, is_closed FROM backtest_input_candles WHERE snapshot_id = $1 ORDER BY timestamp ASC", [saved.id]); validateInputSnapshot(saved, rows.rows.map((row) => candle(row, saved))); return saved; } await client.query("INSERT INTO backtest_input_snapshots (id, pair, pair_metadata, timeframe, dataset_from, dataset_to, candle_count, sha256, created_at) VALUES ($1, $2, $3::jsonb, $4, $5, $6, $7, $8, $9)", [input.id, input.pair, JSON.stringify(input.pairMetadata), input.timeframe, input.range.from, input.range.to, input.candleCount, input.sha256, input.createdAt]); for (const item of candles) await client.query("INSERT INTO backtest_input_candles (snapshot_id, timestamp, open, high, low, close, volume, is_closed) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)", [input.id, item.timestamp, item.open, item.high, item.low, item.close, item.volume, item.isClosed]); const count = await client.query<{ count: number | string }>("SELECT COUNT(*)::int AS count FROM backtest_input_candles WHERE snapshot_id = $1", [input.id]); if (!count.rows[0] || Number(count.rows[0].count) !== input.candleCount) invalidSnapshot(); return input; }); }
  async readInputSnapshot(snapshotId: string) { const head = await this.pool.query<SnapshotRow>("SELECT id, pair, pair_metadata, timeframe, dataset_from, dataset_to, candle_count, sha256, created_at FROM backtest_input_snapshots WHERE id = $1", [snapshotId]); if (!head.rows[0]) return undefined; const metadata = snapshot(head.rows[0]); const rows = await this.pool.query<CandleRow>("SELECT timestamp, open, high, low, close, volume, is_closed FROM backtest_input_candles WHERE snapshot_id = $1 ORDER BY timestamp ASC", [snapshotId]); const candles = rows.rows.map((row) => candle(row, metadata)); validateInputSnapshot(metadata, candles); return { snapshot: metadata, candles }; }
  async createScope(input: StoredBenchmarkScope, idempotencyKey: string): Promise<StoredBenchmarkScope> { await this.pool.query("INSERT INTO backtest_benchmark_scopes (id, owner_user_id, idempotency_key, name, version, dataset_snapshot_id, sentiment_dataset_snapshot, worker_runtime_version, worker_runtime_sha256, evaluation_runtime_version, evaluation_runtime_sha256, simulator_version, simulator_sha256, benchmark_timezone, fill_policy_id, opposite_signal_policy_id, same_candle_ordering_policy_id, deterministic_guarantee, warmup_capacity_candles, initial_capital, fee_rate_percent, slippage_bps, risk_policy, decimal_policy_id, evaluation_policy_id, score_formula_id, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23::jsonb, $24, $25, $26, $27)", [input.id, input.ownerUserId, idempotencyKey, input.name, input.version, input.datasetSnapshotId, input.sentimentDatasetSnapshot ? JSON.stringify(input.sentimentDatasetSnapshot) : null, input.workerRuntimeVersion, input.workerRuntimeSha256, input.evaluationRuntimeVersion, input.evaluationRuntimeSha256, input.simulatorVersion ?? "1.0.0", input.simulatorSha256 ?? "2ed4a4326ba78169d9432c10f05272b01c53a5518ead8ab873be35bd2f1305bf", input.benchmarkTimezone ?? "UTC", input.fillPolicyId ?? "NEXT_OPEN_OHLC_STOP_FIRST_V2", input.oppositeSignalPolicyId ?? "CLOSE_AND_REVERSE_NEXT_OPEN_V1", input.sameCandleOrderingPolicyId ?? "ENTRY_THEN_PROTECTIVE_EXIT_THEN_CLOSE_V1", input.deterministicGuarantee ?? "SEALED_INPUTS_AND_RETAINED_ARTIFACTS", input.warmupCapacityCandles, input.initialCapital, input.feeRatePercent, input.slippageBps, input.riskPolicy ? JSON.stringify(input.riskPolicy) : null, input.decimalPolicyId, input.evaluationPolicyId, input.scoreFormulaId, input.createdAt]); return input; }
  private scopeRows(where: string): string { return `SELECT s.id, s.owner_user_id, s.idempotency_key, s.name, s.version, s.sentiment_dataset_snapshot, s.worker_runtime_version, s.worker_runtime_sha256, s.evaluation_runtime_version, s.evaluation_runtime_sha256, s.simulator_version, s.simulator_sha256, s.benchmark_timezone, s.fill_policy_id, s.opposite_signal_policy_id, s.same_candle_ordering_policy_id, s.deterministic_guarantee, s.warmup_capacity_candles, s.initial_capital, s.fee_rate_percent, s.slippage_bps, s.risk_policy, s.decimal_policy_id, s.evaluation_policy_id, s.score_formula_id, s.created_at, i.id AS snapshot_id, i.created_at AS snapshot_created_at, i.pair, i.pair_metadata, i.timeframe, i.dataset_from, i.dataset_to, i.candle_count, i.sha256 FROM backtest_benchmark_scopes s JOIN backtest_input_snapshots i ON i.id = s.dataset_snapshot_id ${where}`; }
  async findScopeByIdempotency(ownerUserId: string, idempotencyKey: string) { const result = await this.pool.query<ScopeRow>(this.scopeRows("WHERE s.owner_user_id = $1 AND s.idempotency_key = $2"), [ownerUserId, idempotencyKey]); return result.rows[0] ? scope(result.rows[0]) : undefined; }
  async readScope(scopeId: string, ownerUserId?: string) { const ownerClause = ownerUserId ? " AND s.owner_user_id = $2" : ""; const result = await this.pool.query<ScopeRow>(this.scopeRows(`WHERE s.id = $1${ownerClause}`), ownerUserId ? [scopeId, ownerUserId] : [scopeId]); return result.rows[0] ? scope(result.rows[0]) : undefined; }
  async listScopesByOwner(ownerUserId: string) { const result = await this.pool.query<ScopeRow>(this.scopeRows("WHERE s.owner_user_id = $1 ORDER BY s.created_at ASC, s.id ASC"), [ownerUserId]); return result.rows.map(scope); }
  async deleteScope(scopeId: string, ownerUserId: string): Promise<boolean> {
    return this.transaction(async (client) => {
      await client.query("DELETE FROM leaderboard_entries WHERE leaderboard_scope_id = $1", [scopeId]);
      await client.query(
        `DELETE FROM backtest_replay_verifications 
         WHERE experiment_result_id IN (
           SELECT id FROM backtest_experiment_results WHERE leaderboard_scope_id = $1
         )`,
        [scopeId]
      );
      await client.query(
        `DELETE FROM backtest_trades 
         WHERE backtest_attempt_id IN (
           SELECT a.id FROM backtest_attempts a 
           JOIN backtest_candidates c ON c.id = a.candidate_id 
           WHERE c.leaderboard_scope_id = $1
         )`,
        [scopeId]
      );
      await client.query("DELETE FROM backtest_experiment_results WHERE leaderboard_scope_id = $1", [scopeId]);
      await client.query(
        `DELETE FROM backtest_attempts 
         WHERE candidate_id IN (
           SELECT id FROM backtest_candidates WHERE leaderboard_scope_id = $1
         )`,
        [scopeId]
      );
      await client.query(
        `DELETE FROM backtest_queue_dispatches 
         WHERE candidate_id IN (
           SELECT id FROM backtest_candidates WHERE leaderboard_scope_id = $1
         )`,
        [scopeId]
      );
      await client.query("DELETE FROM backtest_candidates WHERE leaderboard_scope_id = $1", [scopeId]);
      await client.query("DELETE FROM search_runs WHERE leaderboard_scope_id = $1", [scopeId]);
      const result = await client.query<{ id: string }>(
        "DELETE FROM backtest_benchmark_scopes WHERE id = $1 AND owner_user_id = $2 RETURNING id",
        [scopeId, ownerUserId]
      );
      return result.rows.length > 0;
    });
  }
  private async candidateFrom(row: CandidateRow): Promise<StoredCandidate> { return { candidateId: row.id, ownerUserId: row.owner_user_id, origin: row.origin, selectionMode: row.selection_mode, searchRunId: row.search_run_id ?? undefined, iterationNumber: row.iteration_number ?? undefined, generatedBy: row.generated_by ?? undefined, fingerprint: row.fingerprint ?? undefined, lineage: row.lineage === null || row.lineage === undefined ? undefined : value<NonNullable<StoredCandidate["lineage"]>>(row.lineage), leaderboardScopeId: row.leaderboard_scope_id, status: row.status, attempts: await this.listAttempts(row.id), maxAttempts: row.max_attempts, activeAttemptNumber: row.active_attempt_number ?? undefined, completionAttemptCount: row.completion_attempt_count, completionMaxAttempts: row.completion_max_attempts, completionNextRetryAt: row.completion_next_retry_at === null ? undefined : date(row.completion_next_retry_at), completionGeneration: row.completion_generation, activeCompletionClaimToken: row.active_completion_claim_token ?? undefined, activeCompletionLeaseExpiresAt: row.active_completion_lease_expires_at === null ? undefined : date(row.active_completion_lease_expires_at), experimentResultId: row.experiment_result_id ?? undefined, failureKind: row.failure_kind ?? undefined, failureCode: row.failure_code ?? undefined, lastError: row.last_error ?? undefined, strategyDefinitions: value<StoredCandidate["strategyDefinitions"]>(row.strategy_definitions), compositeDefinition: value<StoredCandidate["compositeDefinition"]>(row.composite_definition), executionPolicy: row.execution_policy === null || row.execution_policy === undefined ? undefined : value<NonNullable<StoredCandidate["executionPolicy"]>>(row.execution_policy), queueJobId: row.queue_job_id, executionGeneration: row.execution_generation, activeFenceToken: row.active_fence_token ?? undefined, activeLeaseExpiresAt: row.active_lease_expires_at === null ? undefined : date(row.active_lease_expires_at), warmupCandles: row.warmup_candles, createdAt: date(row.created_at), updatedAt: date(row.updated_at) }; }
  private candidateSql(where: string): string { return `SELECT id, owner_user_id, leaderboard_scope_id, search_run_id, iteration_number, generated_by, fingerprint, lineage, origin, selection_mode, status, max_attempts, active_attempt_number, completion_attempt_count, completion_max_attempts, completion_next_retry_at, completion_generation, active_completion_claim_token, active_completion_lease_expires_at, experiment_result_id, failure_kind, failure_code, last_error, queue_job_id, execution_generation, active_fence_token, active_lease_expires_at, warmup_candles, execution_policy, strategy_definitions, composite_definition, created_at, updated_at FROM backtest_candidates ${where}`; }
  async createCandidate(input: StoredCandidate, key?: string): Promise<StoredCandidate> { await this.pool.query("INSERT INTO backtest_candidates (id, owner_user_id, leaderboard_scope_id, search_run_id, iteration_number, generated_by, fingerprint, lineage, origin, selection_mode, status, max_attempts, active_attempt_number, completion_attempt_count, completion_max_attempts, completion_next_retry_at, experiment_result_id, failure_kind, failure_code, last_error, queue_job_id, submission_idempotency_key, warmup_candles, execution_policy, strategy_definitions, composite_definition, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24::jsonb, $25::jsonb, $26::jsonb, $27, $28)", [input.candidateId, input.ownerUserId, input.leaderboardScopeId, input.searchRunId ?? null, input.iterationNumber ?? null, input.generatedBy ?? null, input.fingerprint ?? null, input.lineage ? JSON.stringify(input.lineage) : null, input.origin, input.selectionMode, input.status, input.maxAttempts, input.activeAttemptNumber ?? null, input.completionAttemptCount, input.completionMaxAttempts, input.completionNextRetryAt ?? null, input.experimentResultId ?? null, input.failureKind ?? null, input.failureCode ?? null, input.lastError ?? null, input.queueJobId, key ?? null, input.warmupCandles ?? 0, input.executionPolicy ? JSON.stringify(input.executionPolicy) : null, JSON.stringify(input.strategyDefinitions), JSON.stringify(input.compositeDefinition), input.createdAt, input.updatedAt]); return input; }
  async createQueuedSubmission(input: { candidate: StoredCandidate; dispatch: BacktestDispatch; submissionIdempotencyKey?: string }): Promise<StoredCandidate> {
    const persistedCandidateId = await this.transaction(async (client) => {
      const inserted = await client.query<{ id: string }>("INSERT INTO backtest_candidates (id, owner_user_id, leaderboard_scope_id, search_run_id, iteration_number, generated_by, fingerprint, lineage, origin, selection_mode, status, max_attempts, active_attempt_number, completion_attempt_count, completion_max_attempts, completion_next_retry_at, experiment_result_id, failure_kind, failure_code, last_error, queue_job_id, submission_idempotency_key, warmup_candles, execution_policy, strategy_definitions, composite_definition, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24::jsonb, $25::jsonb, $26::jsonb, $27, $28) ON CONFLICT (search_run_id, iteration_number) DO NOTHING RETURNING id", [input.candidate.candidateId, input.candidate.ownerUserId, input.candidate.leaderboardScopeId, input.candidate.searchRunId ?? null, input.candidate.iterationNumber ?? null, input.candidate.generatedBy ?? null, input.candidate.fingerprint ?? null, input.candidate.lineage ? JSON.stringify(input.candidate.lineage) : null, input.candidate.origin, input.candidate.selectionMode, input.candidate.status, input.candidate.maxAttempts, null, input.candidate.completionAttemptCount, input.candidate.completionMaxAttempts, null, null, null, null, null, input.candidate.queueJobId, input.submissionIdempotencyKey ?? null, input.candidate.warmupCandles ?? 0, input.candidate.executionPolicy ? JSON.stringify(input.candidate.executionPolicy) : null, JSON.stringify(input.candidate.strategyDefinitions), JSON.stringify(input.candidate.compositeDefinition), input.candidate.createdAt, input.candidate.updatedAt]);
      if (inserted.rows[0] || input.candidate.searchRunId === undefined || input.candidate.iterationNumber === undefined) {
        await client.query("INSERT INTO backtest_queue_dispatches (job_id, candidate_id, payload, state, dispatch_attempts, last_error, dispatched_at, created_at, updated_at) VALUES ($1, $2, $3::jsonb, $4, $5, $6, $7, $8, $9)", [input.dispatch.job.jobId, input.candidate.candidateId, JSON.stringify(input.dispatch.job), input.dispatch.state, input.dispatch.dispatchAttempts, input.dispatch.lastError ?? null, input.dispatch.dispatchedAt ?? null, input.dispatch.createdAt, input.dispatch.updatedAt]);
        return input.candidate.candidateId;
      }
      if (input.candidate.searchRunId === undefined || input.candidate.iterationNumber === undefined) throw new Error("BACKTEST_CANDIDATE_DUPLICATE");
      const existing = await client.query<{ id: string }>("SELECT id FROM backtest_candidates WHERE search_run_id = $1 AND iteration_number = $2", [input.candidate.searchRunId, input.candidate.iterationNumber]);
      if (!existing.rows[0]) throw new Error("BACKTEST_CANDIDATE_IDEMPOTENCY_LOOKUP_FAILED");
      return existing.rows[0].id;
    });
    if (persistedCandidateId !== input.candidate.candidateId) {
      const existing = await this.readCandidate(persistedCandidateId);
      if (!existing) throw new Error("BACKTEST_CANDIDATE_IDEMPOTENCY_LOOKUP_FAILED");
      return existing;
    }
    return input.candidate;
  }
  async findCandidateBySubmission(ownerUserId: string, key: string) { const result = await this.pool.query<CandidateRow>(this.candidateSql("WHERE owner_user_id = $1 AND submission_idempotency_key = $2"), [ownerUserId, key]); return result.rows[0] ? this.candidateFrom(result.rows[0]) : undefined; }
  async readCandidate(candidateId: string, ownerUserId?: string) { const ownerClause = ownerUserId ? " AND owner_user_id = $2" : ""; const result = await this.pool.query<CandidateRow>(this.candidateSql(`WHERE id = $1${ownerClause}`), ownerUserId ? [candidateId, ownerUserId] : [candidateId]); return result.rows[0] ? this.candidateFrom(result.rows[0]) : undefined; }
  async updateCandidate(input: StoredCandidate, unitOfWork?: CancellationUnitOfWork): Promise<void> { const client: BacktestingSqlClient = unitOfWork?.query ? { query: (text, values) => unitOfWork.query!(text, values) } : this.pool; await client.query("UPDATE backtest_candidates SET status = $2, active_attempt_number = $3, completion_attempt_count = $4, completion_max_attempts = $5, completion_next_retry_at = $6, completion_generation = $7, active_completion_claim_token = $8, active_completion_lease_expires_at = $9, experiment_result_id = $10, failure_kind = $11, failure_code = $12, last_error = $13, execution_generation = $14, active_fence_token = $15, active_lease_expires_at = $16, updated_at = $17 WHERE id = $1", [input.candidateId, input.status, input.activeAttemptNumber ?? null, input.completionAttemptCount, input.completionMaxAttempts, input.completionNextRetryAt ?? null, input.completionGeneration ?? 0, input.activeCompletionClaimToken ?? null, input.activeCompletionLeaseExpiresAt ?? null, input.experimentResultId ?? null, input.failureKind ?? null, input.failureCode ?? null, input.lastError ?? null, input.executionGeneration ?? 0, input.activeFenceToken ?? null, input.activeLeaseExpiresAt ?? null, input.updatedAt]); }
  async readDispatch(jobId: string) { const result = await this.pool.query<DispatchRow>("SELECT job_id, payload, state, dispatch_attempts, last_error, dispatched_at, created_at, updated_at FROM backtest_queue_dispatches WHERE job_id = $1", [jobId]); return result.rows[0] ? dispatch(result.rows[0]) : undefined; }
  async listPendingDispatches(limit: number) { const result = await this.pool.query<DispatchRow>("SELECT job_id, payload, state, dispatch_attempts, last_error, dispatched_at, created_at, updated_at FROM backtest_queue_dispatches WHERE state = 'PENDING' ORDER BY created_at ASC LIMIT $1", [limit]); return result.rows.map(dispatch); }
  async listQueueRecoveryCandidates(limit: number): Promise<string[]> { const result = await this.pool.query<{ id: string }>("SELECT id FROM backtest_candidates WHERE status IN ('QUEUED', 'BACKTESTING', 'RETRY_WAIT') ORDER BY updated_at ASC LIMIT $1", [limit]); return result.rows.map((row) => row.id); }
  async recoverAbandonedAttempt(input: { candidateId: string; now: string; error: string }): Promise<boolean> {
    return this.transaction(async (client) => {
      const candidate = await client.query<{ status: StoredCandidate["status"]; active_attempt_number: number | null; max_attempts: number; queue_job_id: string }>("SELECT status, active_attempt_number, max_attempts, queue_job_id FROM backtest_candidates WHERE id = $1 AND status = 'BACKTESTING' AND active_lease_expires_at IS NOT NULL AND active_lease_expires_at <= $2 FOR UPDATE", [input.candidateId, input.now]);
      if (!candidate.rows[0]) return false;
      const running = await client.query<{ id: string; attempt_number: number }>("SELECT id, attempt_number FROM backtest_attempts WHERE candidate_id = $1 AND status = 'RUNNING' ORDER BY attempt_number DESC LIMIT 1 FOR UPDATE", [input.candidateId]);
      if (running.rows[0]) await client.query("UPDATE backtest_attempts SET status = 'FAILED', lease_expires_at = NULL, failure_category = 'INFRASTRUCTURE', failure_code = $2, error_message = $2, completed_at = $3 WHERE id = $1 AND status = 'RUNNING'", [running.rows[0].id, input.error, input.now]);
      else {
        const count = await client.query<{ count: number | string }>("SELECT COUNT(*)::int AS count FROM backtest_attempts WHERE candidate_id = $1", [input.candidateId]);
        if (Number(count.rows[0]?.count ?? 0) === 0) await client.query("INSERT INTO backtest_attempts (id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, delivery_attempt_count, failure_category, failure_code, error_message, started_at, completed_at) VALUES ($1, $2, $3, 1, $4, $5, 'FAILED', 0, false, 0, 'INFRASTRUCTURE', $6, $6, $7, $7)", [`${input.candidateId}:recovery:attempt:1`, input.candidateId, candidate.rows[0].queue_job_id, RECOVERY_RUNTIME_VERSION, RECOVERY_RUNTIME_SHA256, input.error, input.now]);
      }
      const attemptNumber = candidate.rows[0].active_attempt_number ?? running.rows[0]?.attempt_number ?? candidate.rows[0].max_attempts;
      const retrying = attemptNumber < candidate.rows[0].max_attempts;
      await client.query("UPDATE backtest_candidates SET status = $2, active_attempt_number = NULL, active_fence_token = NULL, active_lease_expires_at = NULL, failure_kind = $3, failure_code = $4, last_error = $5, updated_at = $6 WHERE id = $1 AND status = 'BACKTESTING'", [input.candidateId, retrying ? "RETRY_WAIT" : "TERMINAL_FAILURE_PENDING", retrying ? null : "INFRASTRUCTURE", retrying ? null : input.error, retrying ? null : input.error, input.now]);
      if (retrying) await client.query("UPDATE backtest_queue_dispatches SET state = 'PENDING', last_error = $2, updated_at = $3 WHERE candidate_id = $1 AND state <> 'CANCELLED'", [input.candidateId, input.error, input.now]);
      return true;
    });
  }
  async markDispatchDispatched(jobId: string, dispatchedAt: string): Promise<void> { await this.pool.query("UPDATE backtest_queue_dispatches SET state = 'DISPATCHED', dispatch_attempts = dispatch_attempts + 1, last_error = NULL, dispatched_at = $2, updated_at = $2 WHERE job_id = $1 AND state <> 'CANCELLED'", [jobId, dispatchedAt]); }
  async markDispatchFailed(jobId: string, error: string, at: string): Promise<void> { await this.pool.query("UPDATE backtest_queue_dispatches SET state = 'PENDING', dispatch_attempts = dispatch_attempts + 1, last_error = $2, updated_at = $3 WHERE job_id = $1 AND state <> 'CANCELLED'", [jobId, error, at]); }
  async markDispatchCancelled(jobId: string, at: string, unitOfWork?: CancellationUnitOfWork): Promise<void> { const client: BacktestingSqlClient = unitOfWork?.query ? { query: (text, values) => unitOfWork.query!(text, values) } : this.pool; await client.query("UPDATE backtest_queue_dispatches SET state = 'CANCELLED', updated_at = $2 WHERE job_id = $1", [jobId, at]); }
  async listCandidatesBySearchRun(searchRunId: string, ownerUserId?: string) { const ownerClause = ownerUserId ? " AND owner_user_id = $2" : ""; const result = await this.pool.query<CandidateRow>(this.candidateSql(`WHERE search_run_id = $1${ownerClause} ORDER BY created_at ASC`), ownerUserId ? [searchRunId, ownerUserId] : [searchRunId]); return Promise.all(result.rows.map((row) => this.candidateFrom(row))); }
  async createAttempt(input: BacktestAttemptAudit): Promise<void> { await this.pool.query("INSERT INTO backtest_attempts (id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, delivery_attempt_count, fence_token, lease_expires_at, failure_category, failure_code, error_message, started_at, completed_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)", [input.attemptId, input.candidateId, input.queueJobId, input.attemptNumber, input.workerRuntimeVersion, input.workerRuntimeSha256, input.status, input.tradeCount, input.auditOnly, input.deliveryAttemptCount ?? 0, input.fenceToken ?? null, input.leaseExpiresAt ?? null, input.failureCategory ?? null, input.failureCode ?? null, input.errorMessage ?? null, input.startedAt, input.completedAt ?? null]); }
  async updateAttempt(input: BacktestAttemptAudit): Promise<void> { await this.pool.query("UPDATE backtest_attempts SET status = $2, trade_count = $3, audit_only = $4, delivery_attempt_count = $5, fence_token = $6, lease_expires_at = $7, failure_category = $8, failure_code = $9, error_message = $10, completed_at = $11 WHERE id = $1", [input.attemptId, input.status, input.tradeCount, input.auditOnly, input.deliveryAttemptCount ?? 0, input.fenceToken ?? null, input.leaseExpiresAt ?? null, input.failureCategory ?? null, input.failureCode ?? null, input.errorMessage ?? null, input.completedAt ?? null]); }
  async readAttempt(attemptId: string, ownerUserId?: string) { const ownerClause = ownerUserId ? " AND c.owner_user_id = $2" : ""; const result = await this.pool.query<AttemptRow>(`SELECT a.id, a.candidate_id, a.queue_job_id, a.attempt_number, a.worker_runtime_version, a.worker_runtime_sha256, a.status, a.trade_count, a.audit_only, a.delivery_attempt_count, a.fence_token, a.lease_expires_at, a.failure_category, a.failure_code, a.error_message, a.started_at, a.completed_at FROM backtest_attempts a JOIN backtest_candidates c ON c.id = a.candidate_id WHERE a.id = $1${ownerClause}`, ownerUserId ? [attemptId, ownerUserId] : [attemptId]); return result.rows[0] ? attempt(result.rows[0]) : undefined; }
  async listAttempts(candidateId: string): Promise<BacktestAttemptProgress[]> { const result = await this.pool.query<AttemptRow>("SELECT id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, delivery_attempt_count, fence_token, lease_expires_at, failure_category, failure_code, error_message, started_at, completed_at FROM backtest_attempts WHERE candidate_id = $1 ORDER BY attempt_number ASC", [candidateId]); return result.rows.map(attempt); }
  async claimWorkerAttempt(input: { candidateId: string; queueJobId: string; deliveryAttempt: number; attemptId: string; fenceToken: string; now: string; leaseExpiresAt: string; workerRuntimeVersion: string; workerRuntimeSha256: string }): Promise<WorkerAttemptClaim | undefined> {
    const claimed = await this.transaction(async (client) => {
      const candidate = await client.query<CandidateRow>(`${this.candidateSql("WHERE id = $1 AND queue_job_id = $2 AND (status IN ('QUEUED', 'RETRY_WAIT') OR (status = 'BACKTESTING' AND active_lease_expires_at <= $3)) FOR UPDATE")}`, [input.candidateId, input.queueJobId, input.now]);
      if (!candidate.rows[0]) return undefined;
      await client.query("UPDATE backtest_candidates SET status = 'BACKTESTING', active_attempt_number = $2, execution_generation = execution_generation + 1, active_fence_token = $3, active_lease_expires_at = $4, updated_at = $5 WHERE id = $1", [input.candidateId, input.deliveryAttempt, input.fenceToken, input.leaseExpiresAt, input.now]);
      const attemptResult = await client.query<AttemptRow>("INSERT INTO backtest_attempts (id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, delivery_attempt_count, fence_token, lease_expires_at, started_at) VALUES ($1, $2, $3, $4, $5, $6, 'RUNNING', 0, false, $4, $7, $8, $9) ON CONFLICT (candidate_id, attempt_number) DO UPDATE SET status = 'RUNNING', delivery_attempt_count = EXCLUDED.delivery_attempt_count, fence_token = EXCLUDED.fence_token, lease_expires_at = EXCLUDED.lease_expires_at, completed_at = NULL, failure_category = NULL, failure_code = NULL, error_message = NULL RETURNING id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, delivery_attempt_count, fence_token, lease_expires_at, failure_category, failure_code, error_message, started_at, completed_at", [input.attemptId, input.candidateId, input.queueJobId, input.deliveryAttempt, input.workerRuntimeVersion, input.workerRuntimeSha256, input.fenceToken, input.leaseExpiresAt, input.now]);
      return attemptResult.rows[0] ? attempt(attemptResult.rows[0]) : undefined;
    });
    if (!claimed) return undefined;
    const candidate = await this.readCandidate(input.candidateId);
    if (!candidate) throw new Error("BACKTEST_PERSISTENCE_INTEGRITY_ERROR");
    return { candidate, attempt: claimed, fenceToken: input.fenceToken };
  }
  async failWorkerAttempt(input: { candidate: StoredCandidate; attempt: BacktestAttemptAudit; fenceToken: string; retrying: boolean; now: string; error: string }): Promise<void> { await this.transaction(async (client) => { const current = await client.query<{ status: StoredCandidate["status"] }>("SELECT status FROM backtest_candidates WHERE id = $1 AND active_fence_token = $2 FOR UPDATE", [input.candidate.candidateId, input.fenceToken]); if (!current.rows[0]) throw new Error("BACKTEST_FENCE_LOST"); const cancelled = current.rows[0].status === "CANCELLED"; const attemptUpdate = await client.query<{ id: string }>("UPDATE backtest_attempts SET status = 'FAILED', lease_expires_at = NULL, failure_category = $3, failure_code = $4, error_message = $4, completed_at = $5 WHERE id = $1 AND fence_token = $2 AND status = 'RUNNING' RETURNING id", [input.attempt.attemptId, input.fenceToken, cancelled ? "CANCELLED_AUDIT" : input.retrying ? "RETRYABLE" : "INFRASTRUCTURE", input.error, input.now]); if (!attemptUpdate.rows[0]) throw new Error("BACKTEST_FENCE_LOST"); const candidateUpdate = await client.query<{ id: string }>("UPDATE backtest_candidates SET status = $3, active_attempt_number = NULL, active_fence_token = NULL, active_lease_expires_at = NULL, failure_kind = $4, failure_code = $5, last_error = $6, updated_at = $7 WHERE id = $1 AND active_fence_token = $2 AND status IN ('BACKTESTING', 'CANCELLED') RETURNING id", [input.candidate.candidateId, input.fenceToken, cancelled ? "CANCELLED" : input.retrying ? "RETRY_WAIT" : "TERMINAL_FAILURE_PENDING", cancelled ? null : input.retrying ? null : "RETRY_EXHAUSTED", cancelled ? null : input.error, cancelled ? null : input.error, input.now]); if (!candidateUpdate.rows[0]) throw new Error("BACKTEST_FENCE_LOST"); }); }
  async repairTerminalQueueFailure(input: { candidateId: string; error: string; now: string }): Promise<void> { await this.transaction(async (client) => { const candidate = await client.query<{ status: StoredCandidate["status"]; queue_job_id: string }>("SELECT status, queue_job_id FROM backtest_candidates WHERE id = $1 FOR UPDATE", [input.candidateId]); if (!candidate.rows[0] || ["COMPLETED", "FAILED", "CANCELLED", "TERMINAL_FAILURE_PENDING"].includes(candidate.rows[0].status)) return; const running = await client.query<{ id: string }>("SELECT id FROM backtest_attempts WHERE candidate_id = $1 AND status = 'RUNNING' ORDER BY attempt_number DESC LIMIT 1 FOR UPDATE", [input.candidateId]); if (running.rows[0]) await client.query("UPDATE backtest_attempts SET status = 'FAILED', lease_expires_at = NULL, failure_category = 'INFRASTRUCTURE', failure_code = $2, error_message = $2, completed_at = $3 WHERE id = $1 AND status = 'RUNNING'", [running.rows[0].id, input.error, input.now]); else { const count = await client.query<{ count: number | string }>("SELECT COUNT(*)::int AS count FROM backtest_attempts WHERE candidate_id = $1", [input.candidateId]); if (Number(count.rows[0]?.count ?? 0) === 0) await client.query("INSERT INTO backtest_attempts (id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, delivery_attempt_count, failure_category, failure_code, error_message, started_at, completed_at) VALUES ($1, $2, $3, 1, $4, $5, 'FAILED', 0, false, 0, 'INFRASTRUCTURE', $6, $6, $7, $7)", [`${input.candidateId}:recovery:attempt:1`, input.candidateId, candidate.rows[0].queue_job_id, RECOVERY_RUNTIME_VERSION, RECOVERY_RUNTIME_SHA256, input.error, input.now]); } await client.query("UPDATE backtest_candidates SET status = 'TERMINAL_FAILURE_PENDING', active_attempt_number = NULL, active_fence_token = NULL, active_lease_expires_at = NULL, failure_kind = 'INFRASTRUCTURE', failure_code = $2, last_error = $2, updated_at = $3 WHERE id = $1 AND status IN ('QUEUED', 'BACKTESTING', 'RETRY_WAIT')", [input.candidateId, input.error, input.now]); }); }
  async persistWorkerSuccess(input: { candidate: StoredCandidate; attempt: BacktestAttemptAudit; result: CompletedBacktestResult; fenceToken: string }): Promise<void> {
    await this.transaction(async (client) => {
      const current = await client.query<{ status: StoredCandidate["status"] }>("SELECT status FROM backtest_candidates WHERE id = $1 AND active_fence_token = $2 FOR UPDATE", [input.candidate.candidateId, input.fenceToken]);
      if (!current.rows[0]) throw new Error("BACKTEST_FENCE_LOST");
      const auditOnly = current.rows[0].status === "CANCELLED";
      const attemptUpdate = await client.query<{ id: string }>("UPDATE backtest_attempts SET status = 'COMPLETED', trade_count = $3, audit_only = $4, lease_expires_at = NULL, completed_at = $5 WHERE id = $1 AND fence_token = $2 AND status = 'RUNNING' RETURNING id", [input.attempt.attemptId, input.fenceToken, input.result.trades.length, auditOnly, input.result.completedAt]);
      if (!attemptUpdate.rows[0]) throw new Error("BACKTEST_FENCE_LOST");
      for (const item of input.result.trades) await this.saveTrade(client, item);
      const candidateUpdate = await client.query<{ id: string }>("UPDATE backtest_candidates SET status = CASE WHEN status = 'CANCELLED' THEN 'CANCELLED' ELSE 'PROCESSING_RESULT' END, active_attempt_number = NULL, active_fence_token = NULL, active_lease_expires_at = NULL, completion_next_retry_at = CASE WHEN status = 'CANCELLED' THEN NULL ELSE $3::timestamptz END, updated_at = $3::timestamptz WHERE id = $1 AND active_fence_token = $2 AND status IN ('BACKTESTING', 'CANCELLED') RETURNING id", [input.candidate.candidateId, input.fenceToken, input.result.completedAt]);
      if (!candidateUpdate.rows[0]) throw new Error("BACKTEST_FENCE_LOST");
    });
  }
  async claimCompletion(input: { candidateId: string; claimToken: string; now: string; leaseExpiresAt: string }): Promise<CompletionProcessingClaim | undefined> {
    const claimed = await this.transaction(async (client) => {
      const result = await client.query<{ id: string }>("UPDATE backtest_candidates SET completion_attempt_count = completion_attempt_count + 1, completion_generation = completion_generation + 1, active_completion_claim_token = $2, active_completion_lease_expires_at = $3, completion_next_retry_at = NULL, updated_at = $4 WHERE id = $1 AND status IN ('PROCESSING_RESULT', 'TERMINAL_FAILURE_PENDING') AND completion_attempt_count < completion_max_attempts AND (completion_next_retry_at IS NULL OR completion_next_retry_at <= $4) AND (active_completion_lease_expires_at IS NULL OR active_completion_lease_expires_at <= $4) RETURNING id", [input.candidateId, input.claimToken, input.leaseExpiresAt, input.now]);
      return result.rows[0] !== undefined;
    });
    if (!claimed) return undefined;
    const candidate = await this.readCandidate(input.candidateId);
    if (!candidate) throw new Error("BACKTEST_PERSISTENCE_INTEGRITY_ERROR");
    return { candidate, claimToken: input.claimToken };
  }
  async listDueCompletions(now: string, limit: number): Promise<string[]> { const result = await this.pool.query<{ id: string }>("SELECT id FROM backtest_candidates WHERE status IN ('PROCESSING_RESULT', 'TERMINAL_FAILURE_PENDING') AND completion_attempt_count < completion_max_attempts AND (completion_next_retry_at IS NULL OR completion_next_retry_at <= $1) AND (active_completion_lease_expires_at IS NULL OR active_completion_lease_expires_at <= $1) ORDER BY updated_at ASC LIMIT $2", [now, limit]); return result.rows.map((row) => row.id); }
  async readLatestCompletedAttempt(candidateId: string): Promise<BacktestAttemptAudit | undefined> { const result = await this.pool.query<AttemptRow>("SELECT id, candidate_id, queue_job_id, attempt_number, worker_runtime_version, worker_runtime_sha256, status, trade_count, audit_only, delivery_attempt_count, fence_token, lease_expires_at, failure_category, failure_code, error_message, started_at, completed_at FROM backtest_attempts WHERE candidate_id = $1 AND status = 'COMPLETED' ORDER BY attempt_number DESC LIMIT 1", [candidateId]); return result.rows[0] ? attempt(result.rows[0]) : undefined; }
  async stageCompletionExperiment(input: StoredExperiment, unitOfWork?: CompletionUnitOfWork): Promise<StoredExperiment> { const client: BacktestingSqlClient = unitOfWork?.query ? { query: (text, values) => unitOfWork.query!(text, values) } : this.pool; const select = "SELECT id, candidate_id, backtest_attempt_id, leaderboard_scope_id, score_formula_id, overall_score, rank_eligible, metrics, created_at FROM backtest_experiment_results WHERE candidate_id = $1"; const existing = await client.query<ExperimentRow>(select, [input.candidateId]); if (existing.rows[0]) return this.experiment(existing.rows[0]); await client.query("INSERT INTO backtest_experiment_results (id, candidate_id, backtest_attempt_id, leaderboard_scope_id, score_formula_id, overall_score, rank_eligible, metrics, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9) ON CONFLICT (candidate_id) DO NOTHING", [input.id, input.candidateId, input.backtestAttemptId, input.leaderboardScopeId, input.scoreFormulaId, input.overallScore, input.rankEligible, JSON.stringify(input.metrics), input.createdAt]); const saved = await client.query<ExperimentRow>(select, [input.candidateId]); return saved.rows[0] ? this.experiment(saved.rows[0]) : input; }
  async finalizeCompletion(input: { candidate: StoredCandidate; experimentId: string; claimToken: string; now: string }, unitOfWork?: CompletionUnitOfWork): Promise<void> { const client: BacktestingSqlClient = unitOfWork?.query ? { query: (text, values) => unitOfWork.query!(text, values) } : this.pool; const result = await client.query<{ id: string }>("UPDATE backtest_candidates SET status = 'COMPLETED', experiment_result_id = $5, active_completion_claim_token = NULL, active_completion_lease_expires_at = NULL, completion_next_retry_at = NULL, updated_at = $6 WHERE id = $1 AND status = 'PROCESSING_RESULT' AND active_completion_claim_token = $2 AND completion_generation = $3 AND active_completion_lease_expires_at > $4 RETURNING id", [input.candidate.candidateId, input.claimToken, input.candidate.completionGeneration ?? 0, input.now, input.experimentId, input.now]); if (!result.rows[0]) throw new Error("BACKTEST_COMPLETION_FENCE_LOST"); }
  async finalizeTerminalFailure(input: { candidate: StoredCandidate; claimToken: string; now: string }): Promise<void> { const result = await this.pool.query<{ id: string }>("UPDATE backtest_candidates SET status = 'FAILED', active_completion_claim_token = NULL, active_completion_lease_expires_at = NULL, completion_next_retry_at = NULL, updated_at = $5 WHERE id = $1 AND status = 'TERMINAL_FAILURE_PENDING' AND active_completion_claim_token = $2 AND completion_generation = $3 AND active_completion_lease_expires_at > $4 RETURNING id", [input.candidate.candidateId, input.claimToken, input.candidate.completionGeneration ?? 0, input.now, input.now]); if (!result.rows[0]) throw new Error("BACKTEST_COMPLETION_FENCE_LOST"); }
  async failCompletion(input: { candidate: StoredCandidate; claimToken: string; retryAt?: string; now: string; error: string }): Promise<void> { const exhausted = input.candidate.completionAttemptCount >= input.candidate.completionMaxAttempts; const result = await this.pool.query<{ id: string }>("UPDATE backtest_candidates SET status = $5, active_completion_claim_token = NULL, active_completion_lease_expires_at = NULL, completion_next_retry_at = $6, failure_kind = $7, failure_code = $8, last_error = $9, updated_at = $10 WHERE id = $1 AND active_completion_claim_token = $2 AND completion_generation = $3 AND active_completion_lease_expires_at > $4 RETURNING id", [input.candidate.candidateId, input.claimToken, input.candidate.completionGeneration ?? 0, input.now, exhausted ? "FAILED" : "PROCESSING_RESULT", exhausted ? null : input.retryAt ?? null, exhausted ? "COMPLETION_PROCESSING" : input.candidate.failureKind ?? null, exhausted ? "COMPLETION_PROCESSING_FAILED" : input.candidate.failureCode ?? null, input.error, input.now]); if (!result.rows[0]) throw new Error("BACKTEST_COMPLETION_FENCE_LOST"); }
  private async saveTrade(client: BacktestingSqlClient, item: Trade): Promise<void> { validateTradeRisk(item); await client.query("INSERT INTO backtest_trades (id, backtest_attempt_id, sequence, pair, settlement_asset, signal, entry_time, market_entry_price, entry_price, stop_loss, take_profit, exit_time, market_exit_price, exit_price, exit_reason, quantity, notional_entry_value, equity_before_trade, equity_after_trade, gross_profit, fee_amount, slippage_bps, slippage_amount, profit, result_percent, result) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26)", [item.id, item.backtestAttemptId, item.sequence, item.pair, item.settlementAsset, item.signal, item.entryTime, item.marketEntryPrice, item.entryPrice, item.stopLoss, item.takeProfit, item.exitTime, item.marketExitPrice, item.exitPrice, item.exitReason, item.quantity, item.notionalEntryValue, item.equityBeforeTrade, item.equityAfterTrade, item.grossProfit, item.feeAmount, item.slippageBps, item.slippageAmount, item.profit, item.resultPercent, item.result]); }
  async completeAttempt(input: { candidate: StoredCandidate; attempt: BacktestAttemptAudit; result: CompletedBacktestResult; metrics: EvaluationMetrics; experiment: StoredExperiment; fenceToken?: string }): Promise<void> { await this.transaction(async (client) => { if (input.fenceToken) { const attemptUpdate = await client.query<{ id: string }>("UPDATE backtest_attempts SET status = $2, trade_count = $3, lease_expires_at = NULL, completed_at = $4 WHERE id = $1 AND fence_token = $5 RETURNING id", [input.attempt.attemptId, input.attempt.status, input.attempt.tradeCount, input.attempt.completedAt, input.fenceToken]); if (!attemptUpdate.rows[0]) throw new Error("BACKTEST_FENCE_LOST"); } else await client.query("UPDATE backtest_attempts SET status = $2, trade_count = $3, lease_expires_at = NULL, completed_at = $4 WHERE id = $1", [input.attempt.attemptId, input.attempt.status, input.attempt.tradeCount, input.attempt.completedAt]); for (const item of input.result.trades) await this.saveTrade(client, item); await client.query("INSERT INTO backtest_experiment_results (id, candidate_id, backtest_attempt_id, leaderboard_scope_id, score_formula_id, overall_score, rank_eligible, metrics, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb, $9) ON CONFLICT (candidate_id) DO NOTHING", [input.experiment.id, input.experiment.candidateId, input.experiment.backtestAttemptId, input.experiment.leaderboardScopeId, input.experiment.scoreFormulaId, input.experiment.overallScore, input.experiment.rankEligible, JSON.stringify(input.metrics), input.experiment.createdAt]); if (input.fenceToken) { const candidateUpdate = await client.query<{ id: string }>("UPDATE backtest_candidates SET status = $3, active_attempt_number = NULL, active_fence_token = NULL, active_lease_expires_at = NULL, completion_attempt_count = $4, experiment_result_id = $5, updated_at = $6 WHERE id = $1 AND active_fence_token = $2 RETURNING id", [input.candidate.candidateId, input.fenceToken, input.candidate.status, input.candidate.completionAttemptCount, input.experiment.id, input.candidate.updatedAt]); if (!candidateUpdate.rows[0]) throw new Error("BACKTEST_FENCE_LOST"); } else await client.query("UPDATE backtest_candidates SET status = $2, active_attempt_number = NULL, active_fence_token = NULL, active_lease_expires_at = NULL, completion_attempt_count = $3, experiment_result_id = $4, updated_at = $5 WHERE id = $1", [input.candidate.candidateId, input.candidate.status, input.candidate.completionAttemptCount, input.experiment.id, input.candidate.updatedAt]); }); }
  async listTrades(attemptId: string) { const result = await this.pool.query<TradeRow>("SELECT id, sequence, pair, settlement_asset, backtest_attempt_id, signal, entry_time, market_entry_price, entry_price, stop_loss, take_profit, exit_time, market_exit_price, exit_price, exit_reason, quantity, notional_entry_value, equity_before_trade, equity_after_trade, gross_profit, fee_amount, slippage_bps, slippage_amount, profit, result_percent, result FROM backtest_trades WHERE backtest_attempt_id = $1 ORDER BY entry_time ASC, sequence ASC, id ASC", [attemptId]); return result.rows.map(trade); }
  async readExperiment(experimentId: string, ownerUserId?: string) { const ownerClause = ownerUserId ? " AND c.owner_user_id = $2" : ""; const result = await this.pool.query<ExperimentRow>(`SELECT r.id, r.candidate_id, r.backtest_attempt_id, r.leaderboard_scope_id, r.score_formula_id, r.overall_score, r.rank_eligible, r.metrics, r.created_at FROM backtest_experiment_results r JOIN backtest_candidates c ON c.id = r.candidate_id WHERE r.id = $1${ownerClause}`, ownerUserId ? [experimentId, ownerUserId] : [experimentId]); return result.rows[0] ? this.experiment(result.rows[0]) : undefined; }
  async findExperimentByCandidate(candidateId: string) { const result = await this.pool.query<ExperimentRow>("SELECT id, candidate_id, backtest_attempt_id, leaderboard_scope_id, score_formula_id, overall_score, rank_eligible, metrics, created_at FROM backtest_experiment_results WHERE candidate_id = $1", [candidateId]); return result.rows[0] ? this.experiment(result.rows[0]) : undefined; }
  async listExperimentsBySearchRun(searchRunId: string, ownerUserId?: string) { const ownerClause = ownerUserId ? " AND c.owner_user_id = $2" : ""; const result = await this.pool.query<ExperimentRow>(`SELECT r.id, r.candidate_id, r.backtest_attempt_id, r.leaderboard_scope_id, r.score_formula_id, r.overall_score, r.rank_eligible, r.metrics, r.created_at FROM backtest_experiment_results r JOIN backtest_candidates c ON c.id = r.candidate_id WHERE c.search_run_id = $1${ownerClause} ORDER BY r.created_at ASC`, ownerUserId ? [searchRunId, ownerUserId] : [searchRunId]); return Promise.all(result.rows.map((row) => this.experiment(row))); }
  async updateExperimentScore(experimentId: string, input: { overallScore: number; rankEligible: boolean }, ownerUserId?: string) { const ownerClause = ownerUserId ? " AND EXISTS (SELECT 1 FROM backtest_candidates c WHERE c.id = r.candidate_id AND c.owner_user_id = $4)" : ""; const values = ownerUserId ? [experimentId, input.overallScore, input.rankEligible, ownerUserId] : [experimentId, input.overallScore, input.rankEligible]; const result = await this.pool.query<ExperimentRow>(`UPDATE backtest_experiment_results AS r SET overall_score = $2, rank_eligible = $3 WHERE r.id = $1${ownerClause} RETURNING r.id, r.candidate_id, r.backtest_attempt_id, r.leaderboard_scope_id, r.score_formula_id, r.overall_score, r.rank_eligible, r.metrics, r.created_at`, values); return result.rows[0] ? this.experiment(result.rows[0]) : undefined; }
  async createReplayVerification(input: StoredReplayVerification): Promise<StoredReplayVerification> { await this.pool.query("INSERT INTO backtest_replay_verifications (id, owner_user_id, experiment_result_id, status, mismatch_sample_limit, created_at) VALUES ($1, $2, $3, 'QUEUED', $4, $5) ON CONFLICT (id) DO NOTHING", [input.replayJobId, input.ownerUserId, input.experimentId, input.mismatchSampleLimit, input.requestedAt]); return input; }
  private replaySql(where: string): string { return `SELECT v.id, v.owner_user_id, v.experiment_result_id, v.status, v.mismatch_sample_limit, v.compared_trade_count, v.mismatch_sample, v.total_mismatch_count, v.truncated, v.failure_code, v.claim_token, v.lease_expires_at, v.created_at, v.started_at, v.completed_at, r.backtest_attempt_id FROM backtest_replay_verifications v JOIN backtest_experiment_results r ON r.id = v.experiment_result_id ${where}`; }
  async readReplayVerification(replayJobId: string, ownerUserId?: string): Promise<StoredReplayVerification | undefined> { const ownerClause = ownerUserId ? " AND v.owner_user_id = $2" : ""; const result = await this.pool.query<ReplayRow>(this.replaySql(`WHERE v.id = $1${ownerClause}`), ownerUserId ? [replayJobId, ownerUserId] : [replayJobId]); return result.rows[0] ? replay(result.rows[0]) : undefined; }
  async claimReplayVerification(input: { replayJobId: string; claimToken: string; now: string; leaseExpiresAt: string }): Promise<StoredReplayVerification | undefined> { const claimed = await this.pool.query<ReplayRow>("UPDATE backtest_replay_verifications SET status = 'RUNNING', claim_token = $2, lease_expires_at = $4, started_at = COALESCE(started_at, $3) WHERE id = $1 AND (status = 'QUEUED' OR (status = 'RUNNING' AND (lease_expires_at IS NULL OR lease_expires_at <= $3))) RETURNING id, owner_user_id, experiment_result_id, status, mismatch_sample_limit, compared_trade_count, mismatch_sample, total_mismatch_count, truncated, failure_code, claim_token, lease_expires_at, created_at, started_at, completed_at", [input.replayJobId, input.claimToken, input.now, input.leaseExpiresAt]); if (!claimed.rows[0]) return undefined; const source = await this.pool.query<{ backtest_attempt_id: string }>("SELECT backtest_attempt_id FROM backtest_experiment_results WHERE id = $1", [claimed.rows[0].experiment_result_id]); return source.rows[0] ? replay({ ...claimed.rows[0], backtest_attempt_id: source.rows[0].backtest_attempt_id }) : undefined; }
  async completeReplayVerification(input: { replayJobId: string; claimToken: string; now: string; result: Extract<ReplayVerificationResult, { status: "MATCH" | "MISMATCH" | "NON_REPLAYABLE" }> }): Promise<void> { const isNonReplayable = input.result.status === "NON_REPLAYABLE"; const terminal = input.result as { comparedTradeCount?: number; mismatches?: Array<{ fieldPath: string; expected: string; actual: string }>; totalMismatchCount?: number; truncated?: boolean; failureCode?: string }; const result = await this.pool.query<{ id: string }>("UPDATE backtest_replay_verifications SET status = $4, compared_trade_count = $5, mismatch_sample = $6::jsonb, total_mismatch_count = $7, truncated = $8, failure_code = $9, claim_token = NULL, lease_expires_at = NULL, completed_at = $3 WHERE id = $1 AND claim_token = $2 AND status = 'RUNNING' AND lease_expires_at > $3 RETURNING id", [input.replayJobId, input.claimToken, input.now, input.result.status, isNonReplayable ? null : terminal.comparedTradeCount, isNonReplayable ? null : JSON.stringify(terminal.mismatches), isNonReplayable ? null : terminal.totalMismatchCount, isNonReplayable ? null : terminal.truncated, isNonReplayable ? terminal.failureCode : null]); if (!result.rows[0]) throw new Error("BACKTEST_REPLAY_FENCE_LOST"); }
  async listReplayVerificationRecovery(nowValue: string, limit: number): Promise<string[]> { const result = await this.pool.query<{ id: string }>("SELECT id FROM backtest_replay_verifications WHERE status = 'QUEUED' OR (status = 'RUNNING' AND (lease_expires_at IS NULL OR lease_expires_at <= $1)) ORDER BY created_at ASC, id ASC LIMIT $2", [nowValue, limit]); return result.rows.map((row) => row.id); }
  private async experiment(row: ExperimentRow): Promise<StoredExperiment> { const candidate = await this.readCandidate(row.candidate_id); const benchmark = await this.readScope(row.leaderboard_scope_id); if (!candidate || !benchmark) throw new Error("BACKTEST_PERSISTENCE_INTEGRITY_ERROR"); const trades = await this.listTrades(row.backtest_attempt_id); const metrics = value<EvaluationMetrics>(row.metrics); const projections = projectAmounts(benchmark.initialCapital, trades); const sourceAttempt = await this.readAttempt(row.backtest_attempt_id); return { id: row.id, ownerUserId: candidate.ownerUserId, candidateId: row.candidate_id, searchRunId: candidate.searchRunId, leaderboardScopeId: row.leaderboard_scope_id, scoreFormulaId: row.score_formula_id, overallScore: number(row.overall_score), rankEligible: row.rank_eligible, backtestAttemptId: row.backtest_attempt_id, compositeDefinitionId: candidate.compositeDefinition.id, compositeDefinition: candidate.compositeDefinition, datasetSnapshot: benchmark.datasetSnapshot, sentimentDatasetSnapshot: benchmark.sentimentDatasetSnapshot, strategyDefinitions: candidate.strategyDefinitions, executionPolicy: candidate.executionPolicy, simulatorVersion: benchmark.simulatorVersion, simulatorSha256: benchmark.simulatorSha256, benchmarkTimezone: benchmark.benchmarkTimezone, fillPolicyId: benchmark.fillPolicyId, oppositeSignalPolicyId: benchmark.oppositeSignalPolicyId, sameCandleOrderingPolicyId: benchmark.sameCandleOrderingPolicyId, deterministicGuarantee: benchmark.deterministicGuarantee, workerRuntimeVersion: sourceAttempt?.workerRuntimeVersion, workerRuntimeSha256: sourceAttempt?.workerRuntimeSha256, evaluationRuntimeVersion: metrics.evaluationRuntimeVersion, evaluationRuntimeSha256: metrics.evaluationRuntimeSha256, decimalPolicyId: benchmark.decimalPolicyId, evaluationPolicyId: benchmark.evaluationPolicyId, feeRatePercent: benchmark.feeRatePercent, slippageBps: benchmark.slippageBps, ...projections, metrics, trades, createdAt: date(row.created_at) }; }
}

export const createPostgresBacktestingDependencies = (pool: TransactionPool, dependencies: Omit<import("../application/ports").BacktestingModuleDependencies, "repository" | "evaluation"> & Partial<Pick<import("../application/ports").BacktestingModuleDependencies, "evaluation">>): import("../application/ports").BacktestingModuleDependencies => ({ ...dependencies, evaluation: dependencies.evaluation ?? createEvaluationModule(), repository: new PostgresBacktestingRepository(pool) });

export const createPostgresCompletionUnitOfWork = async (pool: TransactionPool, input: Pick<CompletionUnitOfWork, "candidateId" | "completionAttemptCount" | "completionClaimToken">): Promise<CompletionUnitOfWork> => {
  if (!pool.connect) return { kind: "COMPLETION", id: `completion-${randomUUID()}`, ...input, enlist: () => undefined, commit: async () => undefined, rollback: async () => undefined };
  const client = await pool.connect();
  await client.query("BEGIN", []);
  let closed = false;
  return {
    kind: "COMPLETION",
    id: `completion-${randomUUID()}`,
    ...input,
    query: <Row>(text: string, values: unknown[]) => client.query<Row>(text, values),
    enlist: () => undefined,
    commit: async () => { if (closed) return; await client.query("COMMIT", []); closed = true; client.release(); },
    rollback: async () => { if (closed) return; try { await client.query("ROLLBACK", []); } finally { closed = true; client.release(); } },
  };
};
